//! Slice 5: `backend/src/handlers/{schema}/generated.rs` emission -- the
//! default `_impl` functions (`find_impl`, `get_impl`, `query_impl`,
//! `aggregate_impl`, `create_impl`, `update_impl`, `delete_impl`, plus one
//! `{method}_impl` per custom method) product-owned handler files import
//! and may override.
//!
//! Ported from `_templates/backend/handlers/schema/generated/_mod.j2`.
//! This product's custom methods all have `provider_routine: null`
//! (confirmed: `grep -c provider_routine: entity_types.yaml` shows every
//! occurrence is `null`), so the `provider_routine`-backed branch is not
//! exercised by any oracle data in this repo -- implemented for fidelity
//! from the template text, not verified byte-for-byte the way the
//! `{% else %}` (not-yet-implemented stub) branch is.

use crate::model::{CustomMethod, EntityType, StandardMethod};

pub fn render(schema_name: &str, entities: &[EntityType]) -> String {
    let snake_1 = snake_1(schema_name);
    let mut out = String::new();
    out.push_str(&format!(
        "#![allow(dead_code)]\n\n//\n// Backend {snake_1}: Generated Handler Defaults\n//    Generated by app_gen.\n//    Product-owned handler modules import these defaults and may override any\n//    operation by defining a local function with the same name and signature.\n//\n"
    ));

    for entity in entities {
        if !has_generated_handler(entity) {
            continue;
        }
        out.push_str(&render_entity_module(&snake_1, entity));
    }

    out
}

fn has_generated_handler(entity: &EntityType) -> bool {
    entity
        .standard_methods
        .as_ref()
        .is_some_and(|m| !m.is_empty())
        || entity
            .custom_methods
            .as_ref()
            .is_some_and(|m| !m.is_empty())
}

fn render_entity_module(schema_rust_name: &str, entity: &EntityType) -> String {
    let pascal_1 = &entity.pascal_1;
    let mut out = String::new();
    out.push_str(&format!("pub(crate) mod {} {{\n", entity.snake_1));
    out.push_str("    #[allow(unused_imports)]\n    use std::sync::Arc;\n\n");
    out.push_str(&format!(
        "    #[allow(unused_imports)]\n    use crate::schemas::{schema_rust_name}::*;\n\n"
    ));
    let query_result_import = if entity.is_table {
        format!("{pascal_1}QueryResult, ")
    } else {
        String::new()
    };
    out.push_str(&format!(
        "    #[allow(unused_imports)]\n    use crate::{{\n        product_api::{{DataAccess, EntityType, HandlerResult, JsonValue, UserAuth}},\n        schemas::common::AggregateResult,\n        schemas::{schema_rust_name}::{{Input{pascal_1}, {pascal_1}Projection, {query_result_import}}},\n    }};\n"
    ));

    if let Some(methods) = &entity.standard_methods {
        for method in methods {
            out.push_str(&render_standard_method(entity, *method));
        }
    }

    if let Some(methods) = &entity.custom_methods {
        for method in methods {
            out.push_str(&render_custom_method(method));
        }
    }

    out.push_str("}\n");
    out
}

/// No blank line ever separates different top-level method blocks
/// (standard-to-standard across method kinds, standard-to-custom, or
/// custom-to-custom) -- confirmed against the oracle: `{%- elif %}`/
/// `{%- endif %}` trim markers around each branch strip that gap. A blank
/// line survives only *within* a single method-kind's own multi-function
/// text (FindById's `find_impl`/`find_by_locator_impl` pair, Query's
/// `query_impl`/`aggregate_impl` pair), since that's literal template text
/// with no trim between them.
fn render_standard_method(entity: &EntityType, method: StandardMethod) -> String {
    let pascal_1 = &entity.pascal_1;
    match method {
        StandardMethod::FindById => format!(
            "    pub(crate) async fn find_impl(user: Option<UserAuth>, data_access: &Arc<DataAccess>, entity_type: &Arc<EntityType>, selections: JsonValue, id: String) -> HandlerResult<Option<{pascal_1}Projection>> {{\n        let res = data_access.find_item::<{pascal_1}Projection>(entity_type.clone(), selections, id, user).await?;\n        Ok(res)\n    }}\n\n    pub(crate) async fn find_by_locator_impl(user: Option<UserAuth>, data_access: &Arc<DataAccess>, entity_type: &Arc<EntityType>, selections: JsonValue, locator: String) -> HandlerResult<Option<{pascal_1}Projection>> {{\n        let res = data_access.find_item_by_locator::<{pascal_1}Projection>(entity_type.clone(), selections, locator, user).await?;\n        Ok(res)\n    }}\n"
        ),
        StandardMethod::GetAll => format!(
            "    pub(crate) async fn get_impl(user: Option<UserAuth>, data_access: &Arc<DataAccess>, entity_type: &Arc<EntityType>, selections: JsonValue) -> HandlerResult<Vec<{pascal_1}Projection>> {{\n        let res = data_access.get_items::<{pascal_1}Projection>(entity_type.clone(), selections, None, user).await?;\n        Ok(res)\n    }}\n"
        ),
        StandardMethod::Query => format!(
            "    pub(crate) async fn query_impl(user: Option<UserAuth>, data_access: &Arc<DataAccess>, entity_type: &Arc<EntityType>, selections: JsonValue, filter: Option<JsonValue>, sort: Option<JsonValue>, skip: i32, limit: i32, after: Option<String>) -> HandlerResult<{pascal_1}QueryResult> {{\n        let res = data_access.query_items::<{pascal_1}Projection>(entity_type.clone(), selections, filter, sort, skip, limit, after, user).await?;\n        let query_res = {pascal_1}QueryResult {{\n            date_time: res.date_time,\n            request_duration: res.request_duration,\n            skip: res.skip,\n            limit: res.limit,\n            page_count: res.page_count,\n            page_index: res.page_index,\n            query_count: res.query_count,\n            next_cursor: res.next_cursor,\n            previous_cursor: res.previous_cursor,\n            items: res.items,\n        }};\n        Ok(query_res)\n    }}\n\n    pub(crate) async fn aggregate_impl(user: Option<UserAuth>, data_access: &Arc<DataAccess>, entity_type: &Arc<EntityType>, filter: Option<JsonValue>, group_by: Option<JsonValue>, metrics: Option<JsonValue>, having: Option<JsonValue>, sort: Option<JsonValue>, skip: i32, limit: i32) -> HandlerResult<AggregateResult> {{\n        let res = data_access.aggregate_items(entity_type.clone(), filter, group_by, metrics, having, sort, skip, limit, user).await?;\n        Ok(res)\n    }}\n"
        ),
        StandardMethod::Create => format!(
            "    pub(crate) async fn create_impl(user: Option<UserAuth>, data_access: &Arc<DataAccess>, entity_type: &Arc<EntityType>, selections: JsonValue, input: Input{pascal_1}) -> HandlerResult<{pascal_1}Projection> {{\n        let res = data_access.create_item::<Input{pascal_1}, {pascal_1}Projection>(entity_type.clone(), selections, input, user).await?;\n        Ok(res)\n    }}\n"
        ),
        StandardMethod::Update => format!(
            "    pub(crate) async fn update_impl(user: Option<UserAuth>, data_access: &Arc<DataAccess>, entity_type: &Arc<EntityType>, selections: JsonValue, input: Input{pascal_1}) -> HandlerResult<{pascal_1}Projection> {{\n        let res = data_access.update_item::<Input{pascal_1}, {pascal_1}Projection>(entity_type.clone(), selections, input, user).await?;\n        Ok(res)\n    }}\n"
        ),
        StandardMethod::Delete => format!(
            "    pub(crate) async fn delete_impl(user: Option<UserAuth>, data_access: &Arc<DataAccess>, entity_type: &Arc<EntityType>, input: Input{pascal_1}) -> HandlerResult<i64> {{\n        let res = data_access.delete_item::<Input{pascal_1}>(entity_type.clone(), input, user).await?;\n        Ok(res)\n    }}\n"
        ),
    }
}

fn render_custom_method(method: &CustomMethod) -> String {
    let args_params: String = method
        .args
        .iter()
        .map(|a| format!("{}: {}, ", a.name, a.arg_type))
        .collect();

    if method.provider_routine.is_some() {
        // Not exercised by this product's oracle (every custom method here
        // has provider_routine: null) -- implemented from the template text
        // for fidelity, not byte-verified.
        return format!(
            "    #[allow(unused)]\n    pub(crate) async fn {}_impl(user: Option<UserAuth>, data_access: &Arc<DataAccess>, entity_type: &Arc<EntityType>, selections: JsonValue, {args_params}) -> HandlerResult<{}> {{\n        Err(anyhow::anyhow!(\"custom method `{}` provider_routine dispatch is not implemented in this port\"))\n    }}\n",
            method.name, method.return_type, method.name
        );
    }

    format!(
        "    #[allow(unused)]\n    pub(crate) async fn {}_impl(user: Option<UserAuth>, data_access: &Arc<DataAccess>, entity_type: &Arc<EntityType>, selections: JsonValue, {args_params}) -> HandlerResult<{}> {{\n        Err(anyhow::anyhow!(\"custom method `{}` is not implemented yet\"))\n    }}\n",
        method.name, method.return_type, method.name
    )
}

fn snake_1(name: &str) -> String {
    use inflector::cases::snakecase::to_snake_case;
    to_snake_case(name)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn model_root() -> std::path::PathBuf {
        std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../.appfw/model")
    }

    fn backend_src_root() -> std::path::PathBuf {
        std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../backend/src")
    }

    fn rustfmt(source: &str) -> String {
        use std::io::Write;
        let mut child = std::process::Command::new("rustfmt")
            .arg("--edition")
            .arg("2021")
            .stdin(std::process::Stdio::piped())
            .stdout(std::process::Stdio::piped())
            .stderr(std::process::Stdio::piped())
            .spawn()
            .expect("rustfmt must be on PATH");
        child
            .stdin
            .take()
            .unwrap()
            .write_all(source.as_bytes())
            .unwrap();
        let output = child.wait_with_output().unwrap();
        assert!(
            output.status.success(),
            "rustfmt failed: {}",
            String::from_utf8_lossy(&output.stderr)
        );
        String::from_utf8(output.stdout).unwrap()
    }

    #[test]
    fn governance_handlers_generated_rs_matches_checked_in_oracle_after_rustfmt() {
        let resolved = crate::load_resolved_entities(&model_root()).expect("model should load");
        let entities = resolved
            .iter()
            .find(|(name, _, _)| name == "governance")
            .unwrap()
            .2
            .clone();

        let rendered = rustfmt(&render("governance", &entities));
        let oracle =
            std::fs::read_to_string(backend_src_root().join("handlers/governance/generated.rs"))
                .expect("read oracle handlers/governance/generated.rs");

        assert_eq!(rendered, oracle);
    }

    #[test]
    fn system_handlers_generated_rs_matches_checked_in_oracle_after_rustfmt() {
        let resolved = crate::load_resolved_entities(&model_root()).expect("model should load");
        let entities = resolved
            .iter()
            .find(|(name, _, _)| name == "system")
            .unwrap()
            .2
            .clone();

        let rendered = rustfmt(&render("system", &entities));
        let oracle =
            std::fs::read_to_string(backend_src_root().join("handlers/system/generated.rs"))
                .expect("read oracle handlers/system/generated.rs");

        assert_eq!(rendered, oracle);
    }
}
