//! Slice 2: Rego policy wrapper generation.
//!
//! Pure templating -- confirmed by diff against this product's checked-in
//! output (`backend/config/generated/schemas/**/*.rego`): the actual authz
//! logic is hand-authored per entity under `.appfw/model/schemas/*/rbac/*.rego`
//! and never touched; the generator only wraps it with boilerplate (package
//! declaration, tenant id constant, deny-by-default, `check_schema_type`,
//! `has_role`/`has_any_role`/`tenant_filter` helpers). One source `.rego`
//! file maps to exactly one output file -- no facet logic, no per-entity
//! customization beyond the schema/entity-type name substitution. Confirmed
//! this product has one hand-authored `.rego` file per entity, including
//! audit companions (`project.rego` AND `project_audit.rego` both exist,
//! hand-authored separately) -- the Rego generator does not need to know
//! about facet expansion at all.
//!
//! Ported from the framework's `rego_gen.rs` (39 lines) + its
//! `_templates/types/rbac/_mod.j2` template, verified byte-for-byte against
//! this product's own checked-in `attachment.rego`.

use std::fs;
use std::path::Path;

use anyhow::{Context, Result};

/// The hardcoded tenant id constant the reference generator's template
/// embeds in every output file. Reproduced verbatim for behavior
/// compatibility -- this product's own hand-authored rule bodies mostly
/// don't call `tenant_filter` at all ("Single-tenant: tenant_filter is
/// never called", per this product's own `attachment.rego` comment), but
/// the wrapper still defines it, matching the reference output exactly.
const PDS_TENANT_ID: &str = "180000";

/// Wrap one hand-authored entity's Rego rule body with the generated
/// boilerplate, producing the exact text the framework's `rbac/_mod.j2`
/// template renders.
pub fn wrap_policy(schema_name: &str, entity_type_name: &str, entity_type_rego: &str) -> String {
    format!(
        "#\n\
         # Generated by app_gen.\n\
         #   - Combines entity_type rego rules into full rego policy file.\n\
         #\n\
         package {schema_name}.{entity_type_name}\n\
         import rego.v1\n\
         \n\
         pds_tenant_id := \"{PDS_TENANT_ID}\"\n\
         \n\
         # Define the default permission to be false (deny by default, filter is absent)\n\
         default access = {{\"allow\": false}}\n\
         \n\
         #\n\
         # access result object will contain allow:boolean and filter:object (if allow == true)\n\
         #\n\
         \n\
         check_schema_type() if {{\n\
         \x20\x20\x20\x20input.schema_name == \"{schema_name}\"\n\
         \x20\x20\x20\x20input.entity_type == \"{entity_type_name}\"\n\
         }}\n\
         \n\
         {entity_type_rego}\n\
         \n\
         # Helper rule to check if a user has any of the required roles\n\
         has_any_role(user, required_roles) if {{\n\
         \x20\x20\x20\x20some role in required_roles\n\
         \x20\x20\x20\x20has_role(user, role)\n\
         }}\n\
         \n\
         # Helper rule to check if a user has a specific role\n\
         has_role(user, role) if {{\n\
         \x20\x20\x20\x20user.roles[_] == role\n\
         }}\n\
         \n\
         # Returns tenant filter for community connect users\n\
         tenant_filter(user) := filter if {{\n\
         \x20\x20\x20\x20# if tenant id is PDS Health id, then return empty filter\n\
         \x20\x20\x20\x20user.tenant_id == pds_tenant_id\n\
         \x20\x20\x20\x20filter := {{}}\n\
         }} else := filter if {{\n\
         \x20\x20\x20\x20# otherwise, return filter to match on the tenant_id value\n\
         \x20\x20\x20\x20filter := {{ \"tenant_id\": user.tenant_id }}\n\
         }}\n"
    )
}

/// Render every `*.rego` file in `rbac_dir` into `output_dir`, one-to-one,
/// preserving the source file's stem as the output file name (which doubles
/// as `entity_type_name`).
pub fn generate_schema_rego(rbac_dir: &Path, output_dir: &Path, schema_name: &str) -> Result<()> {
    if !rbac_dir.exists() {
        return Ok(());
    }
    let mut entries: Vec<_> = fs::read_dir(rbac_dir)
        .with_context(|| format!("could not read {}", rbac_dir.display()))?
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.extension().and_then(|e| e.to_str()) == Some("rego"))
        .collect();
    entries.sort();

    fs::create_dir_all(output_dir)
        .with_context(|| format!("could not create {}", output_dir.display()))?;

    for source_path in entries {
        let entity_type_name = source_path
            .file_stem()
            .and_then(|s| s.to_str())
            .with_context(|| format!("invalid rego file name {}", source_path.display()))?
            .to_string();
        let entity_type_rego = fs::read_to_string(&source_path)
            .with_context(|| format!("could not read {}", source_path.display()))?;
        let wrapped = wrap_policy(schema_name, &entity_type_name, &entity_type_rego);
        let target_path = output_dir.join(format!("{entity_type_name}.rego"));
        fs::write(&target_path, wrapped)
            .with_context(|| format!("could not write {}", target_path.display()))?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn model_root() -> std::path::PathBuf {
        std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../.appfw/model")
    }

    fn backend_config_root() -> std::path::PathBuf {
        std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../backend/config/generated")
    }

    #[test]
    fn wrapped_attachment_policy_matches_checked_in_oracle_byte_for_byte() {
        let source = model_root().join("schemas/governance/rbac/attachment.rego");
        let entity_type_rego = fs::read_to_string(&source).expect("read source rego");
        let wrapped = wrap_policy("governance", "attachment", &entity_type_rego);

        let oracle_path = backend_config_root().join("schemas/governance/attachment.rego");
        let oracle = fs::read_to_string(&oracle_path).expect("read oracle rego");

        assert_eq!(
            wrapped, oracle,
            "generated wrapper must match this product's checked-in app_gen output byte-for-byte"
        );
    }

    #[test]
    fn wrapped_user_policy_matches_checked_in_oracle_byte_for_byte() {
        let source = model_root().join("schemas/system/rbac/user.rego");
        let entity_type_rego = fs::read_to_string(&source).expect("read source rego");
        let wrapped = wrap_policy("system", "user", &entity_type_rego);

        let oracle_path = backend_config_root().join("schemas/system/user.rego");
        let oracle = fs::read_to_string(&oracle_path).expect("read oracle rego");

        assert_eq!(wrapped, oracle);
    }

    #[test]
    fn generate_schema_rego_produces_all_41_governance_policies() {
        let tmp =
            std::env::temp_dir().join(format!("product-gen-rego-test-{}", std::process::id()));
        let rbac_dir = model_root().join("schemas/governance/rbac");
        generate_schema_rego(&rbac_dir, &tmp, "governance").expect("generate should succeed");

        let count = fs::read_dir(&tmp).unwrap().filter(|e| e.is_ok()).count();
        assert_eq!(count, 41);

        fs::remove_dir_all(&tmp).ok();
    }

    /// Every hand-authored `.rego` file across both schemas, wrapped, must
    /// match this product's checked-in `app_gen` output byte-for-byte -- not
    /// just the two samples above. This is the real confirmation slice 2 is
    /// done, not `attachment.rego` and `user.rego` happening to work.
    #[test]
    fn every_governance_and_system_policy_matches_checked_in_oracle_byte_for_byte() {
        let mut checked = 0;
        for schema_name in ["governance", "system"] {
            let rbac_dir = model_root().join(format!("schemas/{schema_name}/rbac"));
            let oracle_dir = backend_config_root().join(format!("schemas/{schema_name}"));
            let mut entries: Vec<_> = fs::read_dir(&rbac_dir)
                .unwrap_or_else(|e| panic!("read {}: {e}", rbac_dir.display()))
                .filter_map(|e| e.ok().map(|e| e.path()))
                .filter(|p| p.extension().and_then(|e| e.to_str()) == Some("rego"))
                .collect();
            entries.sort();

            for source_path in entries {
                let entity_type_name = source_path
                    .file_stem()
                    .and_then(|s| s.to_str())
                    .unwrap()
                    .to_string();
                let entity_type_rego = fs::read_to_string(&source_path).unwrap();
                let wrapped = wrap_policy(schema_name, &entity_type_name, &entity_type_rego);
                let oracle_path = oracle_dir.join(format!("{entity_type_name}.rego"));
                let oracle = fs::read_to_string(&oracle_path)
                    .unwrap_or_else(|e| panic!("read oracle {}: {e}", oracle_path.display()));
                assert_eq!(
                    wrapped,
                    oracle,
                    "mismatch for {schema_name}.{entity_type_name} against {}",
                    oracle_path.display()
                );
                checked += 1;
            }
        }
        assert_eq!(
            checked, 42,
            "expected 41 governance + 1 system policy files"
        );
    }
}
