//! Slice 5: `backend/src/routes/{schema}.rs` emission.
//!
//! **Diverges from the raw framework template on purpose.**
//! `_templates/backend/routes/route/_mod.j2` emits
//! `appfw_runtime::routing::runtime_graphql_schema_routes` /
//! `RuntimeAuthState`, but this product's checked-in `routes/governance.rs`
//! and `routes/system.rs` already use product-owned
//! `crate::platform::{auth::JwtAuthConfig, graphql_gateway}` /
//! `graphql_gateway::mount` instead -- confirmed both files exist
//! (`backend/src/platform/{auth,graphql_gateway}.rs`). This means the
//! routing layer was already migrated off the framework in an earlier,
//! separately-scoped pass (the main plan doc's phase 4, "appfw_runtime's
//! non-generator parts"). Reproducing the raw template literally would
//! *regress* that work by reintroducing the framework types. This port
//! targets the product's current, already-migrated behavior -- the actual
//! checked-in oracle -- not the framework's original template text.

pub fn render(schema_name: &str) -> String {
    let pascal_1 = pascal_1(schema_name);
    let snake_1 = snake_1(schema_name);
    format!(
        "//\n// /backend/src/routes/{pascal_1}.rs\n//    Defines routes for {snake_1} GraphQL requests\n//    Generated by app_gen.\n//\n#![allow(dead_code)]\n\nuse crate::platform::runtime::security::SecurityConfig;\nuse axum::Router;\nuse std::sync::Arc;\n\nuse crate::data::data_access::DataAccess;\nuse crate::handlers::{snake_1}::*;\nuse crate::platform::{{auth::JwtAuthConfig, graphql_gateway}};\n\npub async fn get_routes(data_access: Arc<DataAccess>, auth: JwtAuthConfig, security: SecurityConfig) -> Router {{\n    let {snake_1}_schema = async_graphql::Schema::build({pascal_1}Query::default(), {pascal_1}Mutation::default(), async_graphql::EmptySubscription)\n        .data(data_access.clone())\n        .limit_depth(security.graphql_max_depth)\n        .limit_complexity(security.graphql_max_complexity)\n        .finish();\n    let {snake_1}_introspection_schema = async_graphql::Schema::build({pascal_1}Query::default(), {pascal_1}Mutation::default(), async_graphql::EmptySubscription)\n        .data(data_access.clone())\n        .introspection_only()\n        .finish();\n\n    graphql_gateway::mount(\"/{snake_1}\", {snake_1}_schema, {snake_1}_introspection_schema, auth, security)\n}}\n"
    )
}

fn pascal_1(name: &str) -> String {
    use inflector::cases::pascalcase::{is_pascal_case, to_pascal_case};
    if is_pascal_case(name) {
        name.to_string()
    } else {
        to_pascal_case(name)
    }
}

fn snake_1(name: &str) -> String {
    use inflector::cases::snakecase::to_snake_case;
    to_snake_case(name)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn backend_src_root() -> std::path::PathBuf {
        std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../backend/src")
    }

    fn rustfmt(source: &str) -> String {
        use std::io::Write;
        let mut child = std::process::Command::new("rustfmt")
            .arg("--edition")
            .arg("2021")
            .stdin(std::process::Stdio::piped())
            .stdout(std::process::Stdio::piped())
            .stderr(std::process::Stdio::piped())
            .spawn()
            .expect("rustfmt must be on PATH");
        child
            .stdin
            .take()
            .unwrap()
            .write_all(source.as_bytes())
            .unwrap();
        let output = child.wait_with_output().unwrap();
        assert!(output.status.success(), "rustfmt failed");
        String::from_utf8(output.stdout).unwrap()
    }

    #[test]
    fn governance_route_matches_checked_in_oracle_after_rustfmt() {
        let rendered = rustfmt(&render("governance"));
        let oracle = std::fs::read_to_string(backend_src_root().join("routes/governance.rs"))
            .expect("read oracle routes/governance.rs");
        assert_eq!(rendered, oracle);
    }

    #[test]
    fn system_route_matches_checked_in_oracle_after_rustfmt() {
        let rendered = rustfmt(&render("system"));
        let oracle = std::fs::read_to_string(backend_src_root().join("routes/system.rs"))
            .expect("read oracle routes/system.rs");
        assert_eq!(rendered, oracle);
    }
}
