//! Slice 5: the three top-level `backend/src/{schemas,routes,handlers}/mod.rs`
//! files, driven by `gen_mod_rs` + `_templates/backend/{dir}/mod/_mod.j2`.
//!
//! **`routes/mod.rs` is explicitly out of scope for this port.** Unlike
//! `schemas/mod.rs`/`handlers/mod.rs` (which still match their trivial
//! templates -- one fixed module plus `pub(crate) mod {schema};` per
//! schema), this product's checked-in `routes/mod.rs` has been rewritten
//! far beyond the raw template: it wires JWT auth, the database client
//! provider registry, admin UI routing, and MCP routing directly, none of
//! which comes from `.appfw/model/**` data at all. It's phase 4/5 runtime
//! bootstrapping wiring that happens to retain a "Generated by app_gen"
//! header comment, not model-driven codegen output this generator can (or
//! should) reproduce.

pub fn render_schemas_mod(schema_names: &[String]) -> String {
    render("schemas", "common", schema_names)
}

pub fn render_handlers_mod(schema_names: &[String]) -> String {
    render("handlers", "selections", schema_names)
}

fn render(target_dir_name: &str, fixed_module: &str, schema_names: &[String]) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "//\n// /backend/src/{target_dir_name}/mod.rs\n//    Generated by app_gen.\n//\npub(crate) mod {fixed_module};\n"
    ));
    for schema_name in schema_names {
        out.push_str(&format!("\npub(crate) mod {};\n", snake_1(schema_name)));
    }
    out
}

fn snake_1(name: &str) -> String {
    use inflector::cases::snakecase::to_snake_case;
    to_snake_case(name)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn backend_src_root() -> std::path::PathBuf {
        std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../backend/src")
    }

    fn rustfmt(source: &str) -> String {
        use std::io::Write;
        let mut child = std::process::Command::new("rustfmt")
            .arg("--edition")
            .arg("2021")
            .stdin(std::process::Stdio::piped())
            .stdout(std::process::Stdio::piped())
            .stderr(std::process::Stdio::piped())
            .spawn()
            .expect("rustfmt must be on PATH");
        child
            .stdin
            .take()
            .unwrap()
            .write_all(source.as_bytes())
            .unwrap();
        let output = child.wait_with_output().unwrap();
        assert!(output.status.success(), "rustfmt failed");
        String::from_utf8(output.stdout).unwrap()
    }

    #[test]
    fn schemas_mod_rs_matches_checked_in_oracle_after_rustfmt() {
        let schemas = vec!["governance".to_string(), "system".to_string()];
        let rendered = rustfmt(&render_schemas_mod(&schemas));
        let oracle = std::fs::read_to_string(backend_src_root().join("schemas/mod.rs"))
            .expect("read oracle schemas/mod.rs");
        assert_eq!(rendered, oracle);
    }

    #[test]
    fn handlers_mod_rs_matches_checked_in_oracle_after_rustfmt() {
        let schemas = vec!["governance".to_string(), "system".to_string()];
        let rendered = rustfmt(&render_handlers_mod(&schemas));
        let oracle = std::fs::read_to_string(backend_src_root().join("handlers/mod.rs"))
            .expect("read oracle handlers/mod.rs");
        assert_eq!(rendered, oracle);
    }
}
