--
--    Generated by app_gen.
--    by app_gen/_templates/database/postgresql/seed_sql/_mod.j2
--    Seed data for governance schema (PostgreSQL dialect)
--

DO $$
BEGIN




-- ----------------------------------------------------------------------------
-- User
-- ----------------------------------------------------------------------------


INSERT INTO governance.users (
  id, email, username, full_name, hashed_password, role, is_active, is_verified, created_at
)
VALUES (
  'b0000000-0000-4000-8000-000000000001',

  'admin@abchealth.com',

  'admin',

  'Alex Administrator',

  '$argon2id$v=19$m=19456,t=2,p=1$REPLACE_WITH_REAL_HASH_OF_DEMO1234$REPLACE',

  'ADMIN',

  true,

  true,

  '2026-01-01T00:00:00Z'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO governance.users (
  id, email, username, full_name, hashed_password, role, is_active, is_verified, created_at
)
VALUES (
  'b0000000-0000-4000-8000-000000000002',

  'pm@abchealth.com',

  'pm_user',

  'Priya Manager',

  '$argon2id$v=19$m=19456,t=2,p=1$REPLACE_WITH_REAL_HASH_OF_DEMO1234$REPLACE',

  'PROJECT_MANAGER',

  true,

  true,

  '2026-01-01T00:00:00Z'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO governance.users (
  id, email, username, full_name, hashed_password, role, is_active, is_verified, created_at
)
VALUES (
  'b0000000-0000-4000-8000-000000000003',

  'bta@abchealth.com',

  'bta_user',

  'Bailey Alignment',

  '$argon2id$v=19$m=19456,t=2,p=1$REPLACE_WITH_REAL_HASH_OF_DEMO1234$REPLACE',

  'BTA',

  true,

  true,

  '2026-01-01T00:00:00Z'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO governance.users (
  id, email, username, full_name, hashed_password, role, is_active, is_verified, created_at
)
VALUES (
  'b0000000-0000-4000-8000-000000000004',

  'epmo@abchealth.com',

  'epmo_user',

  'Emery Pmo',

  '$argon2id$v=19$m=19456,t=2,p=1$REPLACE_WITH_REAL_HASH_OF_DEMO1234$REPLACE',

  'EPMO',

  true,

  true,

  '2026-01-01T00:00:00Z'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO governance.users (
  id, email, username, full_name, hashed_password, role, is_active, is_verified, created_at
)
VALUES (
  'b0000000-0000-4000-8000-000000000005',

  'eac@abchealth.com',

  'eac_user',

  'Ellis Architecture',

  '$argon2id$v=19$m=19456,t=2,p=1$REPLACE_WITH_REAL_HASH_OF_DEMO1234$REPLACE',

  'EAC',

  true,

  true,

  '2026-01-01T00:00:00Z'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO governance.users (
  id, email, username, full_name, hashed_password, role, is_active, is_verified, created_at
)
VALUES (
  'b0000000-0000-4000-8000-000000000006',

  'pic@abchealth.com',

  'pic_user',

  'Pat Investment',

  '$argon2id$v=19$m=19456,t=2,p=1$REPLACE_WITH_REAL_HASH_OF_DEMO1234$REPLACE',

  'PIC',

  true,

  true,

  '2026-01-01T00:00:00Z'


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO governance.users (
  id, email, username, full_name, hashed_password, role, is_active, is_verified, created_at
)
VALUES (
  'b0000000-0000-4000-8000-000000000007',

  'finance@abchealth.com',

  'finance_user',

  'Frankie Finance',

  '$argon2id$v=19$m=19456,t=2,p=1$REPLACE_WITH_REAL_HASH_OF_DEMO1234$REPLACE',

  'FINANCE',

  true,

  true,

  '2026-01-01T00:00:00Z'


)
ON CONFLICT (id) DO NOTHING;





-- ----------------------------------------------------------------------------
-- WorkflowDefinition
-- ----------------------------------------------------------------------------


INSERT INTO governance.workflow_definitions (
  id, name, definition_version, description, is_active
)
VALUES (
  'c0000000-0000-4000-8000-000000000001',

  'Standard Project Lifecycle v2',

  1,

  'The 5-phase DAG process for project governance (PROVISIONAL — pending the Excel gate/field matrix, spec 002 P5).',

  true


)
ON CONFLICT (id) DO NOTHING;





-- ----------------------------------------------------------------------------
-- WorkflowStageDefinition
-- ----------------------------------------------------------------------------


INSERT INTO governance.workflow_stage_definitions (
  id, workflow_id, stage_name, stage_code, sequence_order, description, phase_name, assigned_roles, prerequisites, conditions, parallel_execution, auto_advance, sla_days, checklist_template
)
VALUES (
  'c1000000-0000-4000-8000-000000000001',

  'c0000000-0000-4000-8000-000000000001',

  'Intake-BTA',

  'INTAKE_BTA',

  1,

  'BTA Intake review',

  'Intake-BTA',

  ARRAY['admin'],

  NULL,

  '{"rules":[]}'::jsonb,

  false,

  false,

  5,

  ARRAY[]::varchar[]


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO governance.workflow_stage_definitions (
  id, workflow_id, stage_name, stage_code, sequence_order, description, phase_name, assigned_roles, prerequisites, conditions, parallel_execution, auto_advance, sla_days, checklist_template
)
VALUES (
  'c1000000-0000-4000-8000-000000000002',

  'c0000000-0000-4000-8000-000000000001',

  'Intake-EPMO',

  'INTAKE_EPMO',

  1,

  'EPMO Intake review',

  'Intake-EPMO',

  ARRAY['admin'],

  NULL,

  '{"rules":[]}'::jsonb,

  false,

  false,

  5,

  ARRAY[]::varchar[]


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO governance.workflow_stage_definitions (
  id, workflow_id, stage_name, stage_code, sequence_order, description, phase_name, assigned_roles, prerequisites, conditions, parallel_execution, auto_advance, sla_days, checklist_template
)
VALUES (
  'c1000000-0000-4000-8000-000000000003',

  'c0000000-0000-4000-8000-000000000001',

  'BTA-Meeting',

  'BTA_MEETING',

  2,

  'BTA Meeting alignment',

  'BTA-Meeting',

  ARRAY['admin'],

  '{"gates":["INTAKE_BTA"]}'::jsonb,

  '{"rules":[]}'::jsonb,

  false,

  false,

  5,

  ARRAY[]::varchar[]


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO governance.workflow_stage_definitions (
  id, workflow_id, stage_name, stage_code, sequence_order, description, phase_name, assigned_roles, prerequisites, conditions, parallel_execution, auto_advance, sla_days, checklist_template
)
VALUES (
  'c1000000-0000-4000-8000-000000000004',

  'c0000000-0000-4000-8000-000000000001',

  'PM',

  'PM_ASSIGN',

  2,

  'Project Manager assignment',

  'PM',

  ARRAY['admin'],

  '{"gates":["INTAKE_EPMO"]}'::jsonb,

  '{"rules":[]}'::jsonb,

  false,

  false,

  5,

  ARRAY[]::varchar[]


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO governance.workflow_stage_definitions (
  id, workflow_id, stage_name, stage_code, sequence_order, description, phase_name, assigned_roles, prerequisites, conditions, parallel_execution, auto_advance, sla_days, checklist_template
)
VALUES (
  'c1000000-0000-4000-8000-000000000005',

  'c0000000-0000-4000-8000-000000000001',

  'VCR',

  'VCR_REVIEW',

  3,

  'Vendor Compliance Review',

  'VCR',

  ARRAY['admin'],

  '{"gates":["BTA_MEETING","PM_ASSIGN"]}'::jsonb,

  '{"rules":[]}'::jsonb,

  false,

  false,

  5,

  ARRAY[]::varchar[]


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO governance.workflow_stage_definitions (
  id, workflow_id, stage_name, stage_code, sequence_order, description, phase_name, assigned_roles, prerequisites, conditions, parallel_execution, auto_advance, sla_days, checklist_template
)
VALUES (
  'c1000000-0000-4000-8000-000000000006',

  'c0000000-0000-4000-8000-000000000001',

  'VRA',

  'VRA_REVIEW',

  4,

  'Vendor Risk Assessment',

  'VRA',

  ARRAY['admin'],

  '{"gates":["VCR_REVIEW"]}'::jsonb,

  '{"rules":[]}'::jsonb,

  false,

  false,

  5,

  ARRAY[]::varchar[]


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO governance.workflow_stage_definitions (
  id, workflow_id, stage_name, stage_code, sequence_order, description, phase_name, assigned_roles, prerequisites, conditions, parallel_execution, auto_advance, sla_days, checklist_template
)
VALUES (
  'c1000000-0000-4000-8000-000000000007',

  'c0000000-0000-4000-8000-000000000001',

  'EAC',

  'EAC_REVIEW',

  4,

  'Enterprise Architecture Committee',

  'EAC',

  ARRAY['admin'],

  '{"gates":["VCR_REVIEW"]}'::jsonb,

  '{"rules":[]}'::jsonb,

  false,

  false,

  5,

  ARRAY[]::varchar[]


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO governance.workflow_stage_definitions (
  id, workflow_id, stage_name, stage_code, sequence_order, description, phase_name, assigned_roles, prerequisites, conditions, parallel_execution, auto_advance, sla_days, checklist_template
)
VALUES (
  'c1000000-0000-4000-8000-000000000008',

  'c0000000-0000-4000-8000-000000000001',

  'PIC',

  'PIC_REVIEW',

  4,

  'Project Investment Committee',

  'PIC',

  ARRAY['admin'],

  '{"gates":["VCR_REVIEW"]}'::jsonb,

  '{"rules":[]}'::jsonb,

  false,

  false,

  5,

  ARRAY[]::varchar[]


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO governance.workflow_stage_definitions (
  id, workflow_id, stage_name, stage_code, sequence_order, description, phase_name, assigned_roles, prerequisites, conditions, parallel_execution, auto_advance, sla_days, checklist_template
)
VALUES (
  'c1000000-0000-4000-8000-000000000009',

  'c0000000-0000-4000-8000-000000000001',

  'Intake-TRC',

  'INTAKE_TRC',

  5,

  'TRC Intake',

  'Intake-TRC',

  ARRAY['admin'],

  '{"gates":["VRA_REVIEW","EAC_REVIEW","PIC_REVIEW"]}'::jsonb,

  '{"rules":[]}'::jsonb,

  false,

  false,

  5,

  ARRAY[]::varchar[]


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO governance.workflow_stage_definitions (
  id, workflow_id, stage_name, stage_code, sequence_order, description, phase_name, assigned_roles, prerequisites, conditions, parallel_execution, auto_advance, sla_days, checklist_template
)
VALUES (
  'c1000000-0000-4000-8000-000000000010',

  'c0000000-0000-4000-8000-000000000001',

  'Intake-SRA',

  'INTAKE_SRA',

  5,

  'SRA Intake',

  'Intake-SRA',

  ARRAY['admin'],

  '{"gates":["VRA_REVIEW","EAC_REVIEW","PIC_REVIEW"]}'::jsonb,

  '{"rules":[]}'::jsonb,

  false,

  false,

  5,

  ARRAY[]::varchar[]


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO governance.workflow_stage_definitions (
  id, workflow_id, stage_name, stage_code, sequence_order, description, phase_name, assigned_roles, prerequisites, conditions, parallel_execution, auto_advance, sla_days, checklist_template
)
VALUES (
  'c1000000-0000-4000-8000-000000000011',

  'c0000000-0000-4000-8000-000000000001',

  'TRC',

  'TRC_REVIEW',

  6,

  'Technical Review Committee',

  'TRC',

  ARRAY['admin'],

  '{"gates":["INTAKE_TRC"]}'::jsonb,

  '{"rules":[]}'::jsonb,

  false,

  false,

  5,

  ARRAY[]::varchar[]


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO governance.workflow_stage_definitions (
  id, workflow_id, stage_name, stage_code, sequence_order, description, phase_name, assigned_roles, prerequisites, conditions, parallel_execution, auto_advance, sla_days, checklist_template
)
VALUES (
  'c1000000-0000-4000-8000-000000000012',

  'c0000000-0000-4000-8000-000000000001',

  'SRA',

  'SRA_REVIEW',

  6,

  'Security Risk Assessment',

  'SRA',

  ARRAY['admin'],

  '{"gates":["INTAKE_SRA"]}'::jsonb,

  '{"rules":[]}'::jsonb,

  false,

  false,

  5,

  ARRAY[]::varchar[]


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO governance.workflow_stage_definitions (
  id, workflow_id, stage_name, stage_code, sequence_order, description, phase_name, assigned_roles, prerequisites, conditions, parallel_execution, auto_advance, sla_days, checklist_template
)
VALUES (
  'c1000000-0000-4000-8000-000000000013',

  'c0000000-0000-4000-8000-000000000001',

  'APM',

  'APM_REVIEW',

  7,

  'Application Portfolio Management',

  'APM',

  ARRAY['admin'],

  '{"gates":["TRC_REVIEW","SRA_REVIEW"]}'::jsonb,

  '{"rules":[]}'::jsonb,

  false,

  false,

  5,

  ARRAY[]::varchar[]


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO governance.workflow_stage_definitions (
  id, workflow_id, stage_name, stage_code, sequence_order, description, phase_name, assigned_roles, prerequisites, conditions, parallel_execution, auto_advance, sla_days, checklist_template
)
VALUES (
  'c1000000-0000-4000-8000-000000000014',

  'c0000000-0000-4000-8000-000000000001',

  'Intake-ST',

  'INTAKE_ST',

  8,

  'Service Transition Intake',

  'Intake-ST',

  ARRAY['admin'],

  '{"gates":["APM_REVIEW"]}'::jsonb,

  '{"rules":[]}'::jsonb,

  false,

  false,

  5,

  ARRAY[]::varchar[]


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO governance.workflow_stage_definitions (
  id, workflow_id, stage_name, stage_code, sequence_order, description, phase_name, assigned_roles, prerequisites, conditions, parallel_execution, auto_advance, sla_days, checklist_template
)
VALUES (
  'c1000000-0000-4000-8000-000000000015',

  'c0000000-0000-4000-8000-000000000001',

  'ST-Runbook',

  'ST_RUNBOOK',

  9,

  'Service Transition Runbook',

  'ST-Runbook',

  ARRAY['admin'],

  '{"gates":["INTAKE_ST"]}'::jsonb,

  '{"rules":[]}'::jsonb,

  false,

  false,

  5,

  ARRAY[]::varchar[]


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO governance.workflow_stage_definitions (
  id, workflow_id, stage_name, stage_code, sequence_order, description, phase_name, assigned_roles, prerequisites, conditions, parallel_execution, auto_advance, sla_days, checklist_template
)
VALUES (
  'c1000000-0000-4000-8000-000000000016',

  'c0000000-0000-4000-8000-000000000001',

  'TechRB',

  'TECH_RB',

  9,

  'Technical Runbook',

  'TechRB',

  ARRAY['admin'],

  '{"gates":["INTAKE_ST"]}'::jsonb,

  '{"rules":[]}'::jsonb,

  false,

  false,

  5,

  ARRAY[]::varchar[]


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO governance.workflow_stage_definitions (
  id, workflow_id, stage_name, stage_code, sequence_order, description, phase_name, assigned_roles, prerequisites, conditions, parallel_execution, auto_advance, sla_days, checklist_template
)
VALUES (
  'c1000000-0000-4000-8000-000000000017',

  'c0000000-0000-4000-8000-000000000001',

  'Vendor ST',

  'VENDOR_ST',

  9,

  'Vendor Service Transition',

  'Vendor ST',

  ARRAY['admin'],

  '{"gates":["INTAKE_ST"]}'::jsonb,

  '{"rules":[]}'::jsonb,

  false,

  false,

  5,

  ARRAY[]::varchar[]


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO governance.workflow_stage_definitions (
  id, workflow_id, stage_name, stage_code, sequence_order, description, phase_name, assigned_roles, prerequisites, conditions, parallel_execution, auto_advance, sla_days, checklist_template
)
VALUES (
  'c1000000-0000-4000-8000-000000000018',

  'c0000000-0000-4000-8000-000000000001',

  'CAB-CT',

  'CAB_CT',

  10,

  'Change Advisory Board - CT',

  'CAB-CT',

  ARRAY['admin'],

  '{"gates":["ST_RUNBOOK","TECH_RB","VENDOR_ST"]}'::jsonb,

  '{"rules":[]}'::jsonb,

  false,

  false,

  5,

  ARRAY[]::varchar[]


)
ON CONFLICT (id) DO NOTHING;

INSERT INTO governance.workflow_stage_definitions (
  id, workflow_id, stage_name, stage_code, sequence_order, description, phase_name, assigned_roles, prerequisites, conditions, parallel_execution, auto_advance, sla_days, checklist_template
)
VALUES (
  'c1000000-0000-4000-8000-000000000019',

  'c0000000-0000-4000-8000-000000000001',

  'CAB-ER',

  'CAB_ER',

  11,

  'Change Advisory Board - ER',

  'CAB-ER',

  ARRAY['admin'],

  '{"gates":["CAB_CT"]}'::jsonb,

  '{"rules":[]}'::jsonb,

  false,

  false,

  5,

  ARRAY[]::varchar[]


)
ON CONFLICT (id) DO NOTHING;




END $$;
