--
--    Generated by app_gen.
--    by app_gen/_templates/database/mssql/seed_sql/_mod.j2
--    Seed data for governance schema (T-SQL dialect)
--




-- ----------------------------------------------------------------------------
-- User
-- ----------------------------------------------------------------------------


IF NOT EXISTS (SELECT 1 FROM [governance].[users] WHERE [id] = N'b0000000-0000-4000-8000-000000000001')
    INSERT INTO [governance].[users] (
        [id], [email], [username], [full_name], [hashed_password], [role], [is_active], [is_verified], [created_at]
    )
    VALUES (
        N'b0000000-0000-4000-8000-000000000001',
        N'admin@abchealth.com',
        N'admin',
        N'Alex Administrator',
        N'$argon2id$v=19$m=19456,t=2,p=1$REPLACE_WITH_REAL_HASH_OF_DEMO1234$REPLACE',
        N'ADMIN',
        1,
        1,
        N'2026-01-01T00:00:00Z'

    );

IF NOT EXISTS (SELECT 1 FROM [governance].[users] WHERE [id] = N'b0000000-0000-4000-8000-000000000002')
    INSERT INTO [governance].[users] (
        [id], [email], [username], [full_name], [hashed_password], [role], [is_active], [is_verified], [created_at]
    )
    VALUES (
        N'b0000000-0000-4000-8000-000000000002',
        N'pm@abchealth.com',
        N'pm_user',
        N'Priya Manager',
        N'$argon2id$v=19$m=19456,t=2,p=1$REPLACE_WITH_REAL_HASH_OF_DEMO1234$REPLACE',
        N'PROJECT_MANAGER',
        1,
        1,
        N'2026-01-01T00:00:00Z'

    );

IF NOT EXISTS (SELECT 1 FROM [governance].[users] WHERE [id] = N'b0000000-0000-4000-8000-000000000003')
    INSERT INTO [governance].[users] (
        [id], [email], [username], [full_name], [hashed_password], [role], [is_active], [is_verified], [created_at]
    )
    VALUES (
        N'b0000000-0000-4000-8000-000000000003',
        N'bta@abchealth.com',
        N'bta_user',
        N'Bailey Alignment',
        N'$argon2id$v=19$m=19456,t=2,p=1$REPLACE_WITH_REAL_HASH_OF_DEMO1234$REPLACE',
        N'BTA',
        1,
        1,
        N'2026-01-01T00:00:00Z'

    );

IF NOT EXISTS (SELECT 1 FROM [governance].[users] WHERE [id] = N'b0000000-0000-4000-8000-000000000004')
    INSERT INTO [governance].[users] (
        [id], [email], [username], [full_name], [hashed_password], [role], [is_active], [is_verified], [created_at]
    )
    VALUES (
        N'b0000000-0000-4000-8000-000000000004',
        N'epmo@abchealth.com',
        N'epmo_user',
        N'Emery Pmo',
        N'$argon2id$v=19$m=19456,t=2,p=1$REPLACE_WITH_REAL_HASH_OF_DEMO1234$REPLACE',
        N'EPMO',
        1,
        1,
        N'2026-01-01T00:00:00Z'

    );

IF NOT EXISTS (SELECT 1 FROM [governance].[users] WHERE [id] = N'b0000000-0000-4000-8000-000000000005')
    INSERT INTO [governance].[users] (
        [id], [email], [username], [full_name], [hashed_password], [role], [is_active], [is_verified], [created_at]
    )
    VALUES (
        N'b0000000-0000-4000-8000-000000000005',
        N'eac@abchealth.com',
        N'eac_user',
        N'Ellis Architecture',
        N'$argon2id$v=19$m=19456,t=2,p=1$REPLACE_WITH_REAL_HASH_OF_DEMO1234$REPLACE',
        N'EAC',
        1,
        1,
        N'2026-01-01T00:00:00Z'

    );

IF NOT EXISTS (SELECT 1 FROM [governance].[users] WHERE [id] = N'b0000000-0000-4000-8000-000000000006')
    INSERT INTO [governance].[users] (
        [id], [email], [username], [full_name], [hashed_password], [role], [is_active], [is_verified], [created_at]
    )
    VALUES (
        N'b0000000-0000-4000-8000-000000000006',
        N'pic@abchealth.com',
        N'pic_user',
        N'Pat Investment',
        N'$argon2id$v=19$m=19456,t=2,p=1$REPLACE_WITH_REAL_HASH_OF_DEMO1234$REPLACE',
        N'PIC',
        1,
        1,
        N'2026-01-01T00:00:00Z'

    );

IF NOT EXISTS (SELECT 1 FROM [governance].[users] WHERE [id] = N'b0000000-0000-4000-8000-000000000007')
    INSERT INTO [governance].[users] (
        [id], [email], [username], [full_name], [hashed_password], [role], [is_active], [is_verified], [created_at]
    )
    VALUES (
        N'b0000000-0000-4000-8000-000000000007',
        N'finance@abchealth.com',
        N'finance_user',
        N'Frankie Finance',
        N'$argon2id$v=19$m=19456,t=2,p=1$REPLACE_WITH_REAL_HASH_OF_DEMO1234$REPLACE',
        N'FINANCE',
        1,
        1,
        N'2026-01-01T00:00:00Z'

    );





-- ----------------------------------------------------------------------------
-- WorkflowDefinition
-- ----------------------------------------------------------------------------


IF NOT EXISTS (SELECT 1 FROM [governance].[workflow_definitions] WHERE [id] = N'c0000000-0000-4000-8000-000000000001')
    INSERT INTO [governance].[workflow_definitions] (
        [id], [name], [definition_version], [description], [is_active]
    )
    VALUES (
        N'c0000000-0000-4000-8000-000000000001',
        N'Standard Project Lifecycle v2',
        1,
        N'The 5-phase DAG process for project governance (PROVISIONAL — pending the Excel gate/field matrix, spec 002 P5).',
        1

    );





-- ----------------------------------------------------------------------------
-- WorkflowStageDefinition
-- ----------------------------------------------------------------------------


IF NOT EXISTS (SELECT 1 FROM [governance].[workflow_stage_definitions] WHERE [id] = N'c1000000-0000-4000-8000-000000000001')
    INSERT INTO [governance].[workflow_stage_definitions] (
        [id], [workflow_id], [stage_name], [stage_code], [sequence_order], [description], [phase_name], [assigned_roles], [prerequisites], [conditions], [parallel_execution], [auto_advance], [sla_days], [checklist_template]
    )
    VALUES (
        N'c1000000-0000-4000-8000-000000000001',
        N'c0000000-0000-4000-8000-000000000001',
        N'Intake-BTA',
        N'INTAKE_BTA',
        1,
        N'BTA Intake review',
        N'Intake-BTA',
        N'["admin"]',
        NULL,
        N'{"rules":[]}',
        0,
        0,
        5,
        N'[]'

    );

IF NOT EXISTS (SELECT 1 FROM [governance].[workflow_stage_definitions] WHERE [id] = N'c1000000-0000-4000-8000-000000000002')
    INSERT INTO [governance].[workflow_stage_definitions] (
        [id], [workflow_id], [stage_name], [stage_code], [sequence_order], [description], [phase_name], [assigned_roles], [prerequisites], [conditions], [parallel_execution], [auto_advance], [sla_days], [checklist_template]
    )
    VALUES (
        N'c1000000-0000-4000-8000-000000000002',
        N'c0000000-0000-4000-8000-000000000001',
        N'Intake-EPMO',
        N'INTAKE_EPMO',
        1,
        N'EPMO Intake review',
        N'Intake-EPMO',
        N'["admin"]',
        NULL,
        N'{"rules":[]}',
        0,
        0,
        5,
        N'[]'

    );

IF NOT EXISTS (SELECT 1 FROM [governance].[workflow_stage_definitions] WHERE [id] = N'c1000000-0000-4000-8000-000000000003')
    INSERT INTO [governance].[workflow_stage_definitions] (
        [id], [workflow_id], [stage_name], [stage_code], [sequence_order], [description], [phase_name], [assigned_roles], [prerequisites], [conditions], [parallel_execution], [auto_advance], [sla_days], [checklist_template]
    )
    VALUES (
        N'c1000000-0000-4000-8000-000000000003',
        N'c0000000-0000-4000-8000-000000000001',
        N'BTA-Meeting',
        N'BTA_MEETING',
        2,
        N'BTA Meeting alignment',
        N'BTA-Meeting',
        N'["admin"]',
        N'{"gates":["INTAKE_BTA"]}',
        N'{"rules":[]}',
        0,
        0,
        5,
        N'[]'

    );

IF NOT EXISTS (SELECT 1 FROM [governance].[workflow_stage_definitions] WHERE [id] = N'c1000000-0000-4000-8000-000000000004')
    INSERT INTO [governance].[workflow_stage_definitions] (
        [id], [workflow_id], [stage_name], [stage_code], [sequence_order], [description], [phase_name], [assigned_roles], [prerequisites], [conditions], [parallel_execution], [auto_advance], [sla_days], [checklist_template]
    )
    VALUES (
        N'c1000000-0000-4000-8000-000000000004',
        N'c0000000-0000-4000-8000-000000000001',
        N'PM',
        N'PM_ASSIGN',
        2,
        N'Project Manager assignment',
        N'PM',
        N'["admin"]',
        N'{"gates":["INTAKE_EPMO"]}',
        N'{"rules":[]}',
        0,
        0,
        5,
        N'[]'

    );

IF NOT EXISTS (SELECT 1 FROM [governance].[workflow_stage_definitions] WHERE [id] = N'c1000000-0000-4000-8000-000000000005')
    INSERT INTO [governance].[workflow_stage_definitions] (
        [id], [workflow_id], [stage_name], [stage_code], [sequence_order], [description], [phase_name], [assigned_roles], [prerequisites], [conditions], [parallel_execution], [auto_advance], [sla_days], [checklist_template]
    )
    VALUES (
        N'c1000000-0000-4000-8000-000000000005',
        N'c0000000-0000-4000-8000-000000000001',
        N'VCR',
        N'VCR_REVIEW',
        3,
        N'Vendor Compliance Review',
        N'VCR',
        N'["admin"]',
        N'{"gates":["BTA_MEETING","PM_ASSIGN"]}',
        N'{"rules":[]}',
        0,
        0,
        5,
        N'[]'

    );

IF NOT EXISTS (SELECT 1 FROM [governance].[workflow_stage_definitions] WHERE [id] = N'c1000000-0000-4000-8000-000000000006')
    INSERT INTO [governance].[workflow_stage_definitions] (
        [id], [workflow_id], [stage_name], [stage_code], [sequence_order], [description], [phase_name], [assigned_roles], [prerequisites], [conditions], [parallel_execution], [auto_advance], [sla_days], [checklist_template]
    )
    VALUES (
        N'c1000000-0000-4000-8000-000000000006',
        N'c0000000-0000-4000-8000-000000000001',
        N'VRA',
        N'VRA_REVIEW',
        4,
        N'Vendor Risk Assessment',
        N'VRA',
        N'["admin"]',
        N'{"gates":["VCR_REVIEW"]}',
        N'{"rules":[]}',
        0,
        0,
        5,
        N'[]'

    );

IF NOT EXISTS (SELECT 1 FROM [governance].[workflow_stage_definitions] WHERE [id] = N'c1000000-0000-4000-8000-000000000007')
    INSERT INTO [governance].[workflow_stage_definitions] (
        [id], [workflow_id], [stage_name], [stage_code], [sequence_order], [description], [phase_name], [assigned_roles], [prerequisites], [conditions], [parallel_execution], [auto_advance], [sla_days], [checklist_template]
    )
    VALUES (
        N'c1000000-0000-4000-8000-000000000007',
        N'c0000000-0000-4000-8000-000000000001',
        N'EAC',
        N'EAC_REVIEW',
        4,
        N'Enterprise Architecture Committee',
        N'EAC',
        N'["admin"]',
        N'{"gates":["VCR_REVIEW"]}',
        N'{"rules":[]}',
        0,
        0,
        5,
        N'[]'

    );

IF NOT EXISTS (SELECT 1 FROM [governance].[workflow_stage_definitions] WHERE [id] = N'c1000000-0000-4000-8000-000000000008')
    INSERT INTO [governance].[workflow_stage_definitions] (
        [id], [workflow_id], [stage_name], [stage_code], [sequence_order], [description], [phase_name], [assigned_roles], [prerequisites], [conditions], [parallel_execution], [auto_advance], [sla_days], [checklist_template]
    )
    VALUES (
        N'c1000000-0000-4000-8000-000000000008',
        N'c0000000-0000-4000-8000-000000000001',
        N'PIC',
        N'PIC_REVIEW',
        4,
        N'Project Investment Committee',
        N'PIC',
        N'["admin"]',
        N'{"gates":["VCR_REVIEW"]}',
        N'{"rules":[]}',
        0,
        0,
        5,
        N'[]'

    );

IF NOT EXISTS (SELECT 1 FROM [governance].[workflow_stage_definitions] WHERE [id] = N'c1000000-0000-4000-8000-000000000009')
    INSERT INTO [governance].[workflow_stage_definitions] (
        [id], [workflow_id], [stage_name], [stage_code], [sequence_order], [description], [phase_name], [assigned_roles], [prerequisites], [conditions], [parallel_execution], [auto_advance], [sla_days], [checklist_template]
    )
    VALUES (
        N'c1000000-0000-4000-8000-000000000009',
        N'c0000000-0000-4000-8000-000000000001',
        N'Intake-TRC',
        N'INTAKE_TRC',
        5,
        N'TRC Intake',
        N'Intake-TRC',
        N'["admin"]',
        N'{"gates":["VRA_REVIEW","EAC_REVIEW","PIC_REVIEW"]}',
        N'{"rules":[]}',
        0,
        0,
        5,
        N'[]'

    );

IF NOT EXISTS (SELECT 1 FROM [governance].[workflow_stage_definitions] WHERE [id] = N'c1000000-0000-4000-8000-000000000010')
    INSERT INTO [governance].[workflow_stage_definitions] (
        [id], [workflow_id], [stage_name], [stage_code], [sequence_order], [description], [phase_name], [assigned_roles], [prerequisites], [conditions], [parallel_execution], [auto_advance], [sla_days], [checklist_template]
    )
    VALUES (
        N'c1000000-0000-4000-8000-000000000010',
        N'c0000000-0000-4000-8000-000000000001',
        N'Intake-SRA',
        N'INTAKE_SRA',
        5,
        N'SRA Intake',
        N'Intake-SRA',
        N'["admin"]',
        N'{"gates":["VRA_REVIEW","EAC_REVIEW","PIC_REVIEW"]}',
        N'{"rules":[]}',
        0,
        0,
        5,
        N'[]'

    );

IF NOT EXISTS (SELECT 1 FROM [governance].[workflow_stage_definitions] WHERE [id] = N'c1000000-0000-4000-8000-000000000011')
    INSERT INTO [governance].[workflow_stage_definitions] (
        [id], [workflow_id], [stage_name], [stage_code], [sequence_order], [description], [phase_name], [assigned_roles], [prerequisites], [conditions], [parallel_execution], [auto_advance], [sla_days], [checklist_template]
    )
    VALUES (
        N'c1000000-0000-4000-8000-000000000011',
        N'c0000000-0000-4000-8000-000000000001',
        N'TRC',
        N'TRC_REVIEW',
        6,
        N'Technical Review Committee',
        N'TRC',
        N'["admin"]',
        N'{"gates":["INTAKE_TRC"]}',
        N'{"rules":[]}',
        0,
        0,
        5,
        N'[]'

    );

IF NOT EXISTS (SELECT 1 FROM [governance].[workflow_stage_definitions] WHERE [id] = N'c1000000-0000-4000-8000-000000000012')
    INSERT INTO [governance].[workflow_stage_definitions] (
        [id], [workflow_id], [stage_name], [stage_code], [sequence_order], [description], [phase_name], [assigned_roles], [prerequisites], [conditions], [parallel_execution], [auto_advance], [sla_days], [checklist_template]
    )
    VALUES (
        N'c1000000-0000-4000-8000-000000000012',
        N'c0000000-0000-4000-8000-000000000001',
        N'SRA',
        N'SRA_REVIEW',
        6,
        N'Security Risk Assessment',
        N'SRA',
        N'["admin"]',
        N'{"gates":["INTAKE_SRA"]}',
        N'{"rules":[]}',
        0,
        0,
        5,
        N'[]'

    );

IF NOT EXISTS (SELECT 1 FROM [governance].[workflow_stage_definitions] WHERE [id] = N'c1000000-0000-4000-8000-000000000013')
    INSERT INTO [governance].[workflow_stage_definitions] (
        [id], [workflow_id], [stage_name], [stage_code], [sequence_order], [description], [phase_name], [assigned_roles], [prerequisites], [conditions], [parallel_execution], [auto_advance], [sla_days], [checklist_template]
    )
    VALUES (
        N'c1000000-0000-4000-8000-000000000013',
        N'c0000000-0000-4000-8000-000000000001',
        N'APM',
        N'APM_REVIEW',
        7,
        N'Application Portfolio Management',
        N'APM',
        N'["admin"]',
        N'{"gates":["TRC_REVIEW","SRA_REVIEW"]}',
        N'{"rules":[]}',
        0,
        0,
        5,
        N'[]'

    );

IF NOT EXISTS (SELECT 1 FROM [governance].[workflow_stage_definitions] WHERE [id] = N'c1000000-0000-4000-8000-000000000014')
    INSERT INTO [governance].[workflow_stage_definitions] (
        [id], [workflow_id], [stage_name], [stage_code], [sequence_order], [description], [phase_name], [assigned_roles], [prerequisites], [conditions], [parallel_execution], [auto_advance], [sla_days], [checklist_template]
    )
    VALUES (
        N'c1000000-0000-4000-8000-000000000014',
        N'c0000000-0000-4000-8000-000000000001',
        N'Intake-ST',
        N'INTAKE_ST',
        8,
        N'Service Transition Intake',
        N'Intake-ST',
        N'["admin"]',
        N'{"gates":["APM_REVIEW"]}',
        N'{"rules":[]}',
        0,
        0,
        5,
        N'[]'

    );

IF NOT EXISTS (SELECT 1 FROM [governance].[workflow_stage_definitions] WHERE [id] = N'c1000000-0000-4000-8000-000000000015')
    INSERT INTO [governance].[workflow_stage_definitions] (
        [id], [workflow_id], [stage_name], [stage_code], [sequence_order], [description], [phase_name], [assigned_roles], [prerequisites], [conditions], [parallel_execution], [auto_advance], [sla_days], [checklist_template]
    )
    VALUES (
        N'c1000000-0000-4000-8000-000000000015',
        N'c0000000-0000-4000-8000-000000000001',
        N'ST-Runbook',
        N'ST_RUNBOOK',
        9,
        N'Service Transition Runbook',
        N'ST-Runbook',
        N'["admin"]',
        N'{"gates":["INTAKE_ST"]}',
        N'{"rules":[]}',
        0,
        0,
        5,
        N'[]'

    );

IF NOT EXISTS (SELECT 1 FROM [governance].[workflow_stage_definitions] WHERE [id] = N'c1000000-0000-4000-8000-000000000016')
    INSERT INTO [governance].[workflow_stage_definitions] (
        [id], [workflow_id], [stage_name], [stage_code], [sequence_order], [description], [phase_name], [assigned_roles], [prerequisites], [conditions], [parallel_execution], [auto_advance], [sla_days], [checklist_template]
    )
    VALUES (
        N'c1000000-0000-4000-8000-000000000016',
        N'c0000000-0000-4000-8000-000000000001',
        N'TechRB',
        N'TECH_RB',
        9,
        N'Technical Runbook',
        N'TechRB',
        N'["admin"]',
        N'{"gates":["INTAKE_ST"]}',
        N'{"rules":[]}',
        0,
        0,
        5,
        N'[]'

    );

IF NOT EXISTS (SELECT 1 FROM [governance].[workflow_stage_definitions] WHERE [id] = N'c1000000-0000-4000-8000-000000000017')
    INSERT INTO [governance].[workflow_stage_definitions] (
        [id], [workflow_id], [stage_name], [stage_code], [sequence_order], [description], [phase_name], [assigned_roles], [prerequisites], [conditions], [parallel_execution], [auto_advance], [sla_days], [checklist_template]
    )
    VALUES (
        N'c1000000-0000-4000-8000-000000000017',
        N'c0000000-0000-4000-8000-000000000001',
        N'Vendor ST',
        N'VENDOR_ST',
        9,
        N'Vendor Service Transition',
        N'Vendor ST',
        N'["admin"]',
        N'{"gates":["INTAKE_ST"]}',
        N'{"rules":[]}',
        0,
        0,
        5,
        N'[]'

    );

IF NOT EXISTS (SELECT 1 FROM [governance].[workflow_stage_definitions] WHERE [id] = N'c1000000-0000-4000-8000-000000000018')
    INSERT INTO [governance].[workflow_stage_definitions] (
        [id], [workflow_id], [stage_name], [stage_code], [sequence_order], [description], [phase_name], [assigned_roles], [prerequisites], [conditions], [parallel_execution], [auto_advance], [sla_days], [checklist_template]
    )
    VALUES (
        N'c1000000-0000-4000-8000-000000000018',
        N'c0000000-0000-4000-8000-000000000001',
        N'CAB-CT',
        N'CAB_CT',
        10,
        N'Change Advisory Board - CT',
        N'CAB-CT',
        N'["admin"]',
        N'{"gates":["ST_RUNBOOK","TECH_RB","VENDOR_ST"]}',
        N'{"rules":[]}',
        0,
        0,
        5,
        N'[]'

    );

IF NOT EXISTS (SELECT 1 FROM [governance].[workflow_stage_definitions] WHERE [id] = N'c1000000-0000-4000-8000-000000000019')
    INSERT INTO [governance].[workflow_stage_definitions] (
        [id], [workflow_id], [stage_name], [stage_code], [sequence_order], [description], [phase_name], [assigned_roles], [prerequisites], [conditions], [parallel_execution], [auto_advance], [sla_days], [checklist_template]
    )
    VALUES (
        N'c1000000-0000-4000-8000-000000000019',
        N'c0000000-0000-4000-8000-000000000001',
        N'CAB-ER',
        N'CAB_ER',
        11,
        N'Change Advisory Board - ER',
        N'CAB-ER',
        N'["admin"]',
        N'{"gates":["CAB_CT"]}',
        N'{"rules":[]}',
        0,
        0,
        5,
        N'[]'

    );
