--
--    Generated by app_gen.
--    by app_gen/_templates/database/snowflake/seed_sql/_mod.j2
--    Seed data for governance schema (Snowflake dialect)
--




-- ----------------------------------------------------------------------------
-- User
-- ----------------------------------------------------------------------------


INSERT INTO "governance"."users" (
    "id", "email", "username", "full_name", "hashed_password", "role", "is_active", "is_verified", "created_at"
)
SELECT
    'b0000000-0000-4000-8000-000000000001',
    'admin@abchealth.com',
    'admin',
    'Alex Administrator',
    '$argon2id$v=19$m=19456,t=2,p=1$REPLACE_WITH_REAL_HASH_OF_DEMO1234$REPLACE',
    'ADMIN',
    true,
    true,
    '2026-01-01T00:00:00Z'

WHERE NOT EXISTS (
    SELECT 1 FROM "governance"."users" WHERE "id" = 'b0000000-0000-4000-8000-000000000001'
);

INSERT INTO "governance"."users" (
    "id", "email", "username", "full_name", "hashed_password", "role", "is_active", "is_verified", "created_at"
)
SELECT
    'b0000000-0000-4000-8000-000000000002',
    'pm@abchealth.com',
    'pm_user',
    'Priya Manager',
    '$argon2id$v=19$m=19456,t=2,p=1$REPLACE_WITH_REAL_HASH_OF_DEMO1234$REPLACE',
    'PROJECT_MANAGER',
    true,
    true,
    '2026-01-01T00:00:00Z'

WHERE NOT EXISTS (
    SELECT 1 FROM "governance"."users" WHERE "id" = 'b0000000-0000-4000-8000-000000000002'
);

INSERT INTO "governance"."users" (
    "id", "email", "username", "full_name", "hashed_password", "role", "is_active", "is_verified", "created_at"
)
SELECT
    'b0000000-0000-4000-8000-000000000003',
    'bta@abchealth.com',
    'bta_user',
    'Bailey Alignment',
    '$argon2id$v=19$m=19456,t=2,p=1$REPLACE_WITH_REAL_HASH_OF_DEMO1234$REPLACE',
    'BTA',
    true,
    true,
    '2026-01-01T00:00:00Z'

WHERE NOT EXISTS (
    SELECT 1 FROM "governance"."users" WHERE "id" = 'b0000000-0000-4000-8000-000000000003'
);

INSERT INTO "governance"."users" (
    "id", "email", "username", "full_name", "hashed_password", "role", "is_active", "is_verified", "created_at"
)
SELECT
    'b0000000-0000-4000-8000-000000000004',
    'epmo@abchealth.com',
    'epmo_user',
    'Emery Pmo',
    '$argon2id$v=19$m=19456,t=2,p=1$REPLACE_WITH_REAL_HASH_OF_DEMO1234$REPLACE',
    'EPMO',
    true,
    true,
    '2026-01-01T00:00:00Z'

WHERE NOT EXISTS (
    SELECT 1 FROM "governance"."users" WHERE "id" = 'b0000000-0000-4000-8000-000000000004'
);

INSERT INTO "governance"."users" (
    "id", "email", "username", "full_name", "hashed_password", "role", "is_active", "is_verified", "created_at"
)
SELECT
    'b0000000-0000-4000-8000-000000000005',
    'eac@abchealth.com',
    'eac_user',
    'Ellis Architecture',
    '$argon2id$v=19$m=19456,t=2,p=1$REPLACE_WITH_REAL_HASH_OF_DEMO1234$REPLACE',
    'EAC',
    true,
    true,
    '2026-01-01T00:00:00Z'

WHERE NOT EXISTS (
    SELECT 1 FROM "governance"."users" WHERE "id" = 'b0000000-0000-4000-8000-000000000005'
);

INSERT INTO "governance"."users" (
    "id", "email", "username", "full_name", "hashed_password", "role", "is_active", "is_verified", "created_at"
)
SELECT
    'b0000000-0000-4000-8000-000000000006',
    'pic@abchealth.com',
    'pic_user',
    'Pat Investment',
    '$argon2id$v=19$m=19456,t=2,p=1$REPLACE_WITH_REAL_HASH_OF_DEMO1234$REPLACE',
    'PIC',
    true,
    true,
    '2026-01-01T00:00:00Z'

WHERE NOT EXISTS (
    SELECT 1 FROM "governance"."users" WHERE "id" = 'b0000000-0000-4000-8000-000000000006'
);

INSERT INTO "governance"."users" (
    "id", "email", "username", "full_name", "hashed_password", "role", "is_active", "is_verified", "created_at"
)
SELECT
    'b0000000-0000-4000-8000-000000000007',
    'finance@abchealth.com',
    'finance_user',
    'Frankie Finance',
    '$argon2id$v=19$m=19456,t=2,p=1$REPLACE_WITH_REAL_HASH_OF_DEMO1234$REPLACE',
    'FINANCE',
    true,
    true,
    '2026-01-01T00:00:00Z'

WHERE NOT EXISTS (
    SELECT 1 FROM "governance"."users" WHERE "id" = 'b0000000-0000-4000-8000-000000000007'
);





-- ----------------------------------------------------------------------------
-- WorkflowDefinition
-- ----------------------------------------------------------------------------


INSERT INTO "governance"."workflow_definitions" (
    "id", "name", "definition_version", "description", "is_active"
)
SELECT
    'c0000000-0000-4000-8000-000000000001',
    'Standard Project Lifecycle v2',
    1,
    'The 5-phase DAG process for project governance (PROVISIONAL — pending the Excel gate/field matrix, spec 002 P5).',
    true

WHERE NOT EXISTS (
    SELECT 1 FROM "governance"."workflow_definitions" WHERE "id" = 'c0000000-0000-4000-8000-000000000001'
);





-- ----------------------------------------------------------------------------
-- WorkflowStageDefinition
-- ----------------------------------------------------------------------------


INSERT INTO "governance"."workflow_stage_definitions" (
    "id", "workflow_id", "stage_name", "stage_code", "sequence_order", "description", "phase_name", "assigned_roles", "prerequisites", "conditions", "parallel_execution", "auto_advance", "sla_days", "checklist_template"
)
SELECT
    'c1000000-0000-4000-8000-000000000001',
    'c0000000-0000-4000-8000-000000000001',
    'Intake-BTA',
    'INTAKE_BTA',
    1,
    'BTA Intake review',
    'Intake-BTA',
    PARSE_JSON('["admin"]'),
    NULL,
    PARSE_JSON('{"rules":[]}'),
    false,
    false,
    5,
    PARSE_JSON('[]')

WHERE NOT EXISTS (
    SELECT 1 FROM "governance"."workflow_stage_definitions" WHERE "id" = 'c1000000-0000-4000-8000-000000000001'
);

INSERT INTO "governance"."workflow_stage_definitions" (
    "id", "workflow_id", "stage_name", "stage_code", "sequence_order", "description", "phase_name", "assigned_roles", "prerequisites", "conditions", "parallel_execution", "auto_advance", "sla_days", "checklist_template"
)
SELECT
    'c1000000-0000-4000-8000-000000000002',
    'c0000000-0000-4000-8000-000000000001',
    'Intake-EPMO',
    'INTAKE_EPMO',
    1,
    'EPMO Intake review',
    'Intake-EPMO',
    PARSE_JSON('["admin"]'),
    NULL,
    PARSE_JSON('{"rules":[]}'),
    false,
    false,
    5,
    PARSE_JSON('[]')

WHERE NOT EXISTS (
    SELECT 1 FROM "governance"."workflow_stage_definitions" WHERE "id" = 'c1000000-0000-4000-8000-000000000002'
);

INSERT INTO "governance"."workflow_stage_definitions" (
    "id", "workflow_id", "stage_name", "stage_code", "sequence_order", "description", "phase_name", "assigned_roles", "prerequisites", "conditions", "parallel_execution", "auto_advance", "sla_days", "checklist_template"
)
SELECT
    'c1000000-0000-4000-8000-000000000003',
    'c0000000-0000-4000-8000-000000000001',
    'BTA-Meeting',
    'BTA_MEETING',
    2,
    'BTA Meeting alignment',
    'BTA-Meeting',
    PARSE_JSON('["admin"]'),
    PARSE_JSON('{"gates":["INTAKE_BTA"]}'),
    PARSE_JSON('{"rules":[]}'),
    false,
    false,
    5,
    PARSE_JSON('[]')

WHERE NOT EXISTS (
    SELECT 1 FROM "governance"."workflow_stage_definitions" WHERE "id" = 'c1000000-0000-4000-8000-000000000003'
);

INSERT INTO "governance"."workflow_stage_definitions" (
    "id", "workflow_id", "stage_name", "stage_code", "sequence_order", "description", "phase_name", "assigned_roles", "prerequisites", "conditions", "parallel_execution", "auto_advance", "sla_days", "checklist_template"
)
SELECT
    'c1000000-0000-4000-8000-000000000004',
    'c0000000-0000-4000-8000-000000000001',
    'PM',
    'PM_ASSIGN',
    2,
    'Project Manager assignment',
    'PM',
    PARSE_JSON('["admin"]'),
    PARSE_JSON('{"gates":["INTAKE_EPMO"]}'),
    PARSE_JSON('{"rules":[]}'),
    false,
    false,
    5,
    PARSE_JSON('[]')

WHERE NOT EXISTS (
    SELECT 1 FROM "governance"."workflow_stage_definitions" WHERE "id" = 'c1000000-0000-4000-8000-000000000004'
);

INSERT INTO "governance"."workflow_stage_definitions" (
    "id", "workflow_id", "stage_name", "stage_code", "sequence_order", "description", "phase_name", "assigned_roles", "prerequisites", "conditions", "parallel_execution", "auto_advance", "sla_days", "checklist_template"
)
SELECT
    'c1000000-0000-4000-8000-000000000005',
    'c0000000-0000-4000-8000-000000000001',
    'VCR',
    'VCR_REVIEW',
    3,
    'Vendor Compliance Review',
    'VCR',
    PARSE_JSON('["admin"]'),
    PARSE_JSON('{"gates":["BTA_MEETING","PM_ASSIGN"]}'),
    PARSE_JSON('{"rules":[]}'),
    false,
    false,
    5,
    PARSE_JSON('[]')

WHERE NOT EXISTS (
    SELECT 1 FROM "governance"."workflow_stage_definitions" WHERE "id" = 'c1000000-0000-4000-8000-000000000005'
);

INSERT INTO "governance"."workflow_stage_definitions" (
    "id", "workflow_id", "stage_name", "stage_code", "sequence_order", "description", "phase_name", "assigned_roles", "prerequisites", "conditions", "parallel_execution", "auto_advance", "sla_days", "checklist_template"
)
SELECT
    'c1000000-0000-4000-8000-000000000006',
    'c0000000-0000-4000-8000-000000000001',
    'VRA',
    'VRA_REVIEW',
    4,
    'Vendor Risk Assessment',
    'VRA',
    PARSE_JSON('["admin"]'),
    PARSE_JSON('{"gates":["VCR_REVIEW"]}'),
    PARSE_JSON('{"rules":[]}'),
    false,
    false,
    5,
    PARSE_JSON('[]')

WHERE NOT EXISTS (
    SELECT 1 FROM "governance"."workflow_stage_definitions" WHERE "id" = 'c1000000-0000-4000-8000-000000000006'
);

INSERT INTO "governance"."workflow_stage_definitions" (
    "id", "workflow_id", "stage_name", "stage_code", "sequence_order", "description", "phase_name", "assigned_roles", "prerequisites", "conditions", "parallel_execution", "auto_advance", "sla_days", "checklist_template"
)
SELECT
    'c1000000-0000-4000-8000-000000000007',
    'c0000000-0000-4000-8000-000000000001',
    'EAC',
    'EAC_REVIEW',
    4,
    'Enterprise Architecture Committee',
    'EAC',
    PARSE_JSON('["admin"]'),
    PARSE_JSON('{"gates":["VCR_REVIEW"]}'),
    PARSE_JSON('{"rules":[]}'),
    false,
    false,
    5,
    PARSE_JSON('[]')

WHERE NOT EXISTS (
    SELECT 1 FROM "governance"."workflow_stage_definitions" WHERE "id" = 'c1000000-0000-4000-8000-000000000007'
);

INSERT INTO "governance"."workflow_stage_definitions" (
    "id", "workflow_id", "stage_name", "stage_code", "sequence_order", "description", "phase_name", "assigned_roles", "prerequisites", "conditions", "parallel_execution", "auto_advance", "sla_days", "checklist_template"
)
SELECT
    'c1000000-0000-4000-8000-000000000008',
    'c0000000-0000-4000-8000-000000000001',
    'PIC',
    'PIC_REVIEW',
    4,
    'Project Investment Committee',
    'PIC',
    PARSE_JSON('["admin"]'),
    PARSE_JSON('{"gates":["VCR_REVIEW"]}'),
    PARSE_JSON('{"rules":[]}'),
    false,
    false,
    5,
    PARSE_JSON('[]')

WHERE NOT EXISTS (
    SELECT 1 FROM "governance"."workflow_stage_definitions" WHERE "id" = 'c1000000-0000-4000-8000-000000000008'
);

INSERT INTO "governance"."workflow_stage_definitions" (
    "id", "workflow_id", "stage_name", "stage_code", "sequence_order", "description", "phase_name", "assigned_roles", "prerequisites", "conditions", "parallel_execution", "auto_advance", "sla_days", "checklist_template"
)
SELECT
    'c1000000-0000-4000-8000-000000000009',
    'c0000000-0000-4000-8000-000000000001',
    'Intake-TRC',
    'INTAKE_TRC',
    5,
    'TRC Intake',
    'Intake-TRC',
    PARSE_JSON('["admin"]'),
    PARSE_JSON('{"gates":["VRA_REVIEW","EAC_REVIEW","PIC_REVIEW"]}'),
    PARSE_JSON('{"rules":[]}'),
    false,
    false,
    5,
    PARSE_JSON('[]')

WHERE NOT EXISTS (
    SELECT 1 FROM "governance"."workflow_stage_definitions" WHERE "id" = 'c1000000-0000-4000-8000-000000000009'
);

INSERT INTO "governance"."workflow_stage_definitions" (
    "id", "workflow_id", "stage_name", "stage_code", "sequence_order", "description", "phase_name", "assigned_roles", "prerequisites", "conditions", "parallel_execution", "auto_advance", "sla_days", "checklist_template"
)
SELECT
    'c1000000-0000-4000-8000-000000000010',
    'c0000000-0000-4000-8000-000000000001',
    'Intake-SRA',
    'INTAKE_SRA',
    5,
    'SRA Intake',
    'Intake-SRA',
    PARSE_JSON('["admin"]'),
    PARSE_JSON('{"gates":["VRA_REVIEW","EAC_REVIEW","PIC_REVIEW"]}'),
    PARSE_JSON('{"rules":[]}'),
    false,
    false,
    5,
    PARSE_JSON('[]')

WHERE NOT EXISTS (
    SELECT 1 FROM "governance"."workflow_stage_definitions" WHERE "id" = 'c1000000-0000-4000-8000-000000000010'
);

INSERT INTO "governance"."workflow_stage_definitions" (
    "id", "workflow_id", "stage_name", "stage_code", "sequence_order", "description", "phase_name", "assigned_roles", "prerequisites", "conditions", "parallel_execution", "auto_advance", "sla_days", "checklist_template"
)
SELECT
    'c1000000-0000-4000-8000-000000000011',
    'c0000000-0000-4000-8000-000000000001',
    'TRC',
    'TRC_REVIEW',
    6,
    'Technical Review Committee',
    'TRC',
    PARSE_JSON('["admin"]'),
    PARSE_JSON('{"gates":["INTAKE_TRC"]}'),
    PARSE_JSON('{"rules":[]}'),
    false,
    false,
    5,
    PARSE_JSON('[]')

WHERE NOT EXISTS (
    SELECT 1 FROM "governance"."workflow_stage_definitions" WHERE "id" = 'c1000000-0000-4000-8000-000000000011'
);

INSERT INTO "governance"."workflow_stage_definitions" (
    "id", "workflow_id", "stage_name", "stage_code", "sequence_order", "description", "phase_name", "assigned_roles", "prerequisites", "conditions", "parallel_execution", "auto_advance", "sla_days", "checklist_template"
)
SELECT
    'c1000000-0000-4000-8000-000000000012',
    'c0000000-0000-4000-8000-000000000001',
    'SRA',
    'SRA_REVIEW',
    6,
    'Security Risk Assessment',
    'SRA',
    PARSE_JSON('["admin"]'),
    PARSE_JSON('{"gates":["INTAKE_SRA"]}'),
    PARSE_JSON('{"rules":[]}'),
    false,
    false,
    5,
    PARSE_JSON('[]')

WHERE NOT EXISTS (
    SELECT 1 FROM "governance"."workflow_stage_definitions" WHERE "id" = 'c1000000-0000-4000-8000-000000000012'
);

INSERT INTO "governance"."workflow_stage_definitions" (
    "id", "workflow_id", "stage_name", "stage_code", "sequence_order", "description", "phase_name", "assigned_roles", "prerequisites", "conditions", "parallel_execution", "auto_advance", "sla_days", "checklist_template"
)
SELECT
    'c1000000-0000-4000-8000-000000000013',
    'c0000000-0000-4000-8000-000000000001',
    'APM',
    'APM_REVIEW',
    7,
    'Application Portfolio Management',
    'APM',
    PARSE_JSON('["admin"]'),
    PARSE_JSON('{"gates":["TRC_REVIEW","SRA_REVIEW"]}'),
    PARSE_JSON('{"rules":[]}'),
    false,
    false,
    5,
    PARSE_JSON('[]')

WHERE NOT EXISTS (
    SELECT 1 FROM "governance"."workflow_stage_definitions" WHERE "id" = 'c1000000-0000-4000-8000-000000000013'
);

INSERT INTO "governance"."workflow_stage_definitions" (
    "id", "workflow_id", "stage_name", "stage_code", "sequence_order", "description", "phase_name", "assigned_roles", "prerequisites", "conditions", "parallel_execution", "auto_advance", "sla_days", "checklist_template"
)
SELECT
    'c1000000-0000-4000-8000-000000000014',
    'c0000000-0000-4000-8000-000000000001',
    'Intake-ST',
    'INTAKE_ST',
    8,
    'Service Transition Intake',
    'Intake-ST',
    PARSE_JSON('["admin"]'),
    PARSE_JSON('{"gates":["APM_REVIEW"]}'),
    PARSE_JSON('{"rules":[]}'),
    false,
    false,
    5,
    PARSE_JSON('[]')

WHERE NOT EXISTS (
    SELECT 1 FROM "governance"."workflow_stage_definitions" WHERE "id" = 'c1000000-0000-4000-8000-000000000014'
);

INSERT INTO "governance"."workflow_stage_definitions" (
    "id", "workflow_id", "stage_name", "stage_code", "sequence_order", "description", "phase_name", "assigned_roles", "prerequisites", "conditions", "parallel_execution", "auto_advance", "sla_days", "checklist_template"
)
SELECT
    'c1000000-0000-4000-8000-000000000015',
    'c0000000-0000-4000-8000-000000000001',
    'ST-Runbook',
    'ST_RUNBOOK',
    9,
    'Service Transition Runbook',
    'ST-Runbook',
    PARSE_JSON('["admin"]'),
    PARSE_JSON('{"gates":["INTAKE_ST"]}'),
    PARSE_JSON('{"rules":[]}'),
    false,
    false,
    5,
    PARSE_JSON('[]')

WHERE NOT EXISTS (
    SELECT 1 FROM "governance"."workflow_stage_definitions" WHERE "id" = 'c1000000-0000-4000-8000-000000000015'
);

INSERT INTO "governance"."workflow_stage_definitions" (
    "id", "workflow_id", "stage_name", "stage_code", "sequence_order", "description", "phase_name", "assigned_roles", "prerequisites", "conditions", "parallel_execution", "auto_advance", "sla_days", "checklist_template"
)
SELECT
    'c1000000-0000-4000-8000-000000000016',
    'c0000000-0000-4000-8000-000000000001',
    'TechRB',
    'TECH_RB',
    9,
    'Technical Runbook',
    'TechRB',
    PARSE_JSON('["admin"]'),
    PARSE_JSON('{"gates":["INTAKE_ST"]}'),
    PARSE_JSON('{"rules":[]}'),
    false,
    false,
    5,
    PARSE_JSON('[]')

WHERE NOT EXISTS (
    SELECT 1 FROM "governance"."workflow_stage_definitions" WHERE "id" = 'c1000000-0000-4000-8000-000000000016'
);

INSERT INTO "governance"."workflow_stage_definitions" (
    "id", "workflow_id", "stage_name", "stage_code", "sequence_order", "description", "phase_name", "assigned_roles", "prerequisites", "conditions", "parallel_execution", "auto_advance", "sla_days", "checklist_template"
)
SELECT
    'c1000000-0000-4000-8000-000000000017',
    'c0000000-0000-4000-8000-000000000001',
    'Vendor ST',
    'VENDOR_ST',
    9,
    'Vendor Service Transition',
    'Vendor ST',
    PARSE_JSON('["admin"]'),
    PARSE_JSON('{"gates":["INTAKE_ST"]}'),
    PARSE_JSON('{"rules":[]}'),
    false,
    false,
    5,
    PARSE_JSON('[]')

WHERE NOT EXISTS (
    SELECT 1 FROM "governance"."workflow_stage_definitions" WHERE "id" = 'c1000000-0000-4000-8000-000000000017'
);

INSERT INTO "governance"."workflow_stage_definitions" (
    "id", "workflow_id", "stage_name", "stage_code", "sequence_order", "description", "phase_name", "assigned_roles", "prerequisites", "conditions", "parallel_execution", "auto_advance", "sla_days", "checklist_template"
)
SELECT
    'c1000000-0000-4000-8000-000000000018',
    'c0000000-0000-4000-8000-000000000001',
    'CAB-CT',
    'CAB_CT',
    10,
    'Change Advisory Board - CT',
    'CAB-CT',
    PARSE_JSON('["admin"]'),
    PARSE_JSON('{"gates":["ST_RUNBOOK","TECH_RB","VENDOR_ST"]}'),
    PARSE_JSON('{"rules":[]}'),
    false,
    false,
    5,
    PARSE_JSON('[]')

WHERE NOT EXISTS (
    SELECT 1 FROM "governance"."workflow_stage_definitions" WHERE "id" = 'c1000000-0000-4000-8000-000000000018'
);

INSERT INTO "governance"."workflow_stage_definitions" (
    "id", "workflow_id", "stage_name", "stage_code", "sequence_order", "description", "phase_name", "assigned_roles", "prerequisites", "conditions", "parallel_execution", "auto_advance", "sla_days", "checklist_template"
)
SELECT
    'c1000000-0000-4000-8000-000000000019',
    'c0000000-0000-4000-8000-000000000001',
    'CAB-ER',
    'CAB_ER',
    11,
    'Change Advisory Board - ER',
    'CAB-ER',
    PARSE_JSON('["admin"]'),
    PARSE_JSON('{"gates":["CAB_CT"]}'),
    PARSE_JSON('{"rules":[]}'),
    false,
    false,
    5,
    PARSE_JSON('[]')

WHERE NOT EXISTS (
    SELECT 1 FROM "governance"."workflow_stage_definitions" WHERE "id" = 'c1000000-0000-4000-8000-000000000019'
);
