--
--    Generated by app_gen.
--    by app_gen/_templates/database/snowflake/create_tables_sql/_mod.j2
--    Defines storage tables for entity_types (Snowflake dialect).
--

CREATE SCHEMA IF NOT EXISTS "governance";


CREATE TABLE IF NOT EXISTS "governance"."attachments"
(
    "id" VARCHAR NOT NULL DEFAULT UUID_STRING() PRIMARY KEY
    ,"project_id" VARCHAR
    ,"file_name" VARCHAR
    ,"file_type" VARCHAR
    ,"file_size" NUMBER(10,0)
    ,"s3_key" VARCHAR
    ,"s3_url" VARCHAR
    ,"upload_status" VARCHAR
    ,"uploaded_by_id" VARCHAR
    ,"ai_extracted" BOOLEAN
    ,"ai_extraction_data" VARIANT
    ,"uploaded_at" TIMESTAMP_TZ
    ,"version" NUMBER(19,0) NOT NULL DEFAULT 0
    ,"record_locator" VARCHAR NOT NULL DEFAULT ('rl_' || REPLACE(UUID_STRING(), '-', ''))
);


ALTER TABLE "governance"."attachments"
    ADD COLUMN IF NOT EXISTS "project_id" VARCHAR;

ALTER TABLE "governance"."attachments"
    ADD COLUMN IF NOT EXISTS "file_name" VARCHAR;

ALTER TABLE "governance"."attachments"
    ADD COLUMN IF NOT EXISTS "file_type" VARCHAR;

ALTER TABLE "governance"."attachments"
    ADD COLUMN IF NOT EXISTS "file_size" NUMBER(10,0);

ALTER TABLE "governance"."attachments"
    ADD COLUMN IF NOT EXISTS "s3_key" VARCHAR;

ALTER TABLE "governance"."attachments"
    ADD COLUMN IF NOT EXISTS "s3_url" VARCHAR;

ALTER TABLE "governance"."attachments"
    ADD COLUMN IF NOT EXISTS "upload_status" VARCHAR;

ALTER TABLE "governance"."attachments"
    ADD COLUMN IF NOT EXISTS "uploaded_by_id" VARCHAR;

ALTER TABLE "governance"."attachments"
    ADD COLUMN IF NOT EXISTS "ai_extracted" BOOLEAN;

ALTER TABLE "governance"."attachments"
    ADD COLUMN IF NOT EXISTS "ai_extraction_data" VARIANT;

ALTER TABLE "governance"."attachments"
    ADD COLUMN IF NOT EXISTS "uploaded_at" TIMESTAMP_TZ;

ALTER TABLE "governance"."attachments"
    ADD COLUMN IF NOT EXISTS "version" NUMBER(19,0) NOT NULL DEFAULT 0;

ALTER TABLE "governance"."attachments"
    ADD COLUMN IF NOT EXISTS "record_locator" VARCHAR;
UPDATE "governance"."attachments"
    SET "record_locator" = ('rl_' || REPLACE(UUID_STRING(), '-', ''))
    WHERE "record_locator" IS NULL;
ALTER TABLE "governance"."attachments"
    ALTER COLUMN "record_locator" SET NOT NULL;



CREATE TABLE IF NOT EXISTS "governance"."audit_events"
(
    "id" VARCHAR NOT NULL DEFAULT UUID_STRING() PRIMARY KEY
    ,"project_id" VARCHAR
    ,"entity_type" VARCHAR
    ,"entity_id" VARCHAR
    ,"action" VARCHAR
    ,"old_values" VARIANT
    ,"new_values" VARIANT
    ,"performed_by_id" VARCHAR
    ,"ip_address" VARCHAR
    ,"user_agent" VARCHAR
    ,"performed_at" TIMESTAMP_TZ
    ,"record_locator" VARCHAR NOT NULL DEFAULT ('rl_' || REPLACE(UUID_STRING(), '-', ''))
);


ALTER TABLE "governance"."audit_events"
    ADD COLUMN IF NOT EXISTS "project_id" VARCHAR;

ALTER TABLE "governance"."audit_events"
    ADD COLUMN IF NOT EXISTS "entity_type" VARCHAR;

ALTER TABLE "governance"."audit_events"
    ADD COLUMN IF NOT EXISTS "entity_id" VARCHAR;

ALTER TABLE "governance"."audit_events"
    ADD COLUMN IF NOT EXISTS "action" VARCHAR;

ALTER TABLE "governance"."audit_events"
    ADD COLUMN IF NOT EXISTS "old_values" VARIANT;

ALTER TABLE "governance"."audit_events"
    ADD COLUMN IF NOT EXISTS "new_values" VARIANT;

ALTER TABLE "governance"."audit_events"
    ADD COLUMN IF NOT EXISTS "performed_by_id" VARCHAR;

ALTER TABLE "governance"."audit_events"
    ADD COLUMN IF NOT EXISTS "ip_address" VARCHAR;

ALTER TABLE "governance"."audit_events"
    ADD COLUMN IF NOT EXISTS "user_agent" VARCHAR;

ALTER TABLE "governance"."audit_events"
    ADD COLUMN IF NOT EXISTS "performed_at" TIMESTAMP_TZ;

ALTER TABLE "governance"."audit_events"
    ADD COLUMN IF NOT EXISTS "record_locator" VARCHAR;
UPDATE "governance"."audit_events"
    SET "record_locator" = ('rl_' || REPLACE(UUID_STRING(), '-', ''))
    WHERE "record_locator" IS NULL;
ALTER TABLE "governance"."audit_events"
    ALTER COLUMN "record_locator" SET NOT NULL;



CREATE TABLE IF NOT EXISTS "governance"."checklist_items"
(
    "id" VARCHAR NOT NULL DEFAULT UUID_STRING() PRIMARY KEY
    ,"task_id" VARCHAR
    ,"item_text" VARCHAR
    ,"is_completed" BOOLEAN
    ,"completed_by_id" VARCHAR
    ,"completed_at" TIMESTAMP_TZ
    ,"sequence_order" NUMBER(10,0)
    ,"record_locator" VARCHAR NOT NULL DEFAULT ('rl_' || REPLACE(UUID_STRING(), '-', ''))
);


ALTER TABLE "governance"."checklist_items"
    ADD COLUMN IF NOT EXISTS "task_id" VARCHAR;

ALTER TABLE "governance"."checklist_items"
    ADD COLUMN IF NOT EXISTS "item_text" VARCHAR;

ALTER TABLE "governance"."checklist_items"
    ADD COLUMN IF NOT EXISTS "is_completed" BOOLEAN;

ALTER TABLE "governance"."checklist_items"
    ADD COLUMN IF NOT EXISTS "completed_by_id" VARCHAR;

ALTER TABLE "governance"."checklist_items"
    ADD COLUMN IF NOT EXISTS "completed_at" TIMESTAMP_TZ;

ALTER TABLE "governance"."checklist_items"
    ADD COLUMN IF NOT EXISTS "sequence_order" NUMBER(10,0);

ALTER TABLE "governance"."checklist_items"
    ADD COLUMN IF NOT EXISTS "record_locator" VARCHAR;
UPDATE "governance"."checklist_items"
    SET "record_locator" = ('rl_' || REPLACE(UUID_STRING(), '-', ''))
    WHERE "record_locator" IS NULL;
ALTER TABLE "governance"."checklist_items"
    ALTER COLUMN "record_locator" SET NOT NULL;



CREATE TABLE IF NOT EXISTS "governance"."comments"
(
    "id" VARCHAR NOT NULL DEFAULT UUID_STRING() PRIMARY KEY
    ,"project_id" VARCHAR
    ,"task_id" VARCHAR
    ,"gate_review_id" VARCHAR
    ,"author_id" VARCHAR
    ,"content" VARCHAR
    ,"parent_id" VARCHAR
    ,"is_internal" BOOLEAN
    ,"created_at" TIMESTAMP_TZ
    ,"updated_at" TIMESTAMP_TZ
    ,"record_locator" VARCHAR NOT NULL DEFAULT ('rl_' || REPLACE(UUID_STRING(), '-', ''))
);


ALTER TABLE "governance"."comments"
    ADD COLUMN IF NOT EXISTS "project_id" VARCHAR;

ALTER TABLE "governance"."comments"
    ADD COLUMN IF NOT EXISTS "task_id" VARCHAR;

ALTER TABLE "governance"."comments"
    ADD COLUMN IF NOT EXISTS "gate_review_id" VARCHAR;

ALTER TABLE "governance"."comments"
    ADD COLUMN IF NOT EXISTS "author_id" VARCHAR;

ALTER TABLE "governance"."comments"
    ADD COLUMN IF NOT EXISTS "content" VARCHAR;

ALTER TABLE "governance"."comments"
    ADD COLUMN IF NOT EXISTS "parent_id" VARCHAR;

ALTER TABLE "governance"."comments"
    ADD COLUMN IF NOT EXISTS "is_internal" BOOLEAN;

ALTER TABLE "governance"."comments"
    ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP_TZ;

ALTER TABLE "governance"."comments"
    ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP_TZ;

ALTER TABLE "governance"."comments"
    ADD COLUMN IF NOT EXISTS "record_locator" VARCHAR;
UPDATE "governance"."comments"
    SET "record_locator" = ('rl_' || REPLACE(UUID_STRING(), '-', ''))
    WHERE "record_locator" IS NULL;
ALTER TABLE "governance"."comments"
    ALTER COLUMN "record_locator" SET NOT NULL;



CREATE TABLE IF NOT EXISTS "governance"."email_queue_items"
(
    "id" VARCHAR NOT NULL DEFAULT UUID_STRING() PRIMARY KEY
    ,"to_email" VARCHAR
    ,"to_name" VARCHAR
    ,"subject" VARCHAR
    ,"template_name" VARCHAR
    ,"template_data" VARIANT
    ,"html_body" VARCHAR
    ,"text_body" VARCHAR
    ,"status" VARCHAR
    ,"attempts" NUMBER(10,0)
    ,"max_attempts" NUMBER(10,0)
    ,"error_message" VARCHAR
    ,"scheduled_at" TIMESTAMP_TZ
    ,"sent_at" TIMESTAMP_TZ
    ,"created_at" TIMESTAMP_TZ
    ,"record_locator" VARCHAR NOT NULL DEFAULT ('rl_' || REPLACE(UUID_STRING(), '-', ''))
);


ALTER TABLE "governance"."email_queue_items"
    ADD COLUMN IF NOT EXISTS "to_email" VARCHAR;

ALTER TABLE "governance"."email_queue_items"
    ADD COLUMN IF NOT EXISTS "to_name" VARCHAR;

ALTER TABLE "governance"."email_queue_items"
    ADD COLUMN IF NOT EXISTS "subject" VARCHAR;

ALTER TABLE "governance"."email_queue_items"
    ADD COLUMN IF NOT EXISTS "template_name" VARCHAR;

ALTER TABLE "governance"."email_queue_items"
    ADD COLUMN IF NOT EXISTS "template_data" VARIANT;

ALTER TABLE "governance"."email_queue_items"
    ADD COLUMN IF NOT EXISTS "html_body" VARCHAR;

ALTER TABLE "governance"."email_queue_items"
    ADD COLUMN IF NOT EXISTS "text_body" VARCHAR;

ALTER TABLE "governance"."email_queue_items"
    ADD COLUMN IF NOT EXISTS "status" VARCHAR;

ALTER TABLE "governance"."email_queue_items"
    ADD COLUMN IF NOT EXISTS "attempts" NUMBER(10,0);

ALTER TABLE "governance"."email_queue_items"
    ADD COLUMN IF NOT EXISTS "max_attempts" NUMBER(10,0);

ALTER TABLE "governance"."email_queue_items"
    ADD COLUMN IF NOT EXISTS "error_message" VARCHAR;

ALTER TABLE "governance"."email_queue_items"
    ADD COLUMN IF NOT EXISTS "scheduled_at" TIMESTAMP_TZ;

ALTER TABLE "governance"."email_queue_items"
    ADD COLUMN IF NOT EXISTS "sent_at" TIMESTAMP_TZ;

ALTER TABLE "governance"."email_queue_items"
    ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP_TZ;

ALTER TABLE "governance"."email_queue_items"
    ADD COLUMN IF NOT EXISTS "record_locator" VARCHAR;
UPDATE "governance"."email_queue_items"
    SET "record_locator" = ('rl_' || REPLACE(UUID_STRING(), '-', ''))
    WHERE "record_locator" IS NULL;
ALTER TABLE "governance"."email_queue_items"
    ALTER COLUMN "record_locator" SET NOT NULL;



CREATE TABLE IF NOT EXISTS "governance"."gate_reviews"
(
    "id" VARCHAR NOT NULL DEFAULT UUID_STRING() PRIMARY KEY
    ,"project_id" VARCHAR
    ,"gate_code" VARCHAR
    ,"gate_name" VARCHAR
    ,"committee" VARCHAR
    ,"assigned_role" VARCHAR
    ,"status" VARCHAR
    ,"decision" VARCHAR
    ,"decision_by_id" VARCHAR
    ,"decision_at" TIMESTAMP_TZ
    ,"decision_notes" VARCHAR
    ,"checklist_items" VARIANT
    ,"submitted_at" TIMESTAMP_TZ
    ,"due_date" TIMESTAMP_TZ
    ,"priority" VARCHAR
    ,"version" NUMBER(19,0) NOT NULL DEFAULT 0
    ,"record_locator" VARCHAR NOT NULL DEFAULT ('rl_' || REPLACE(UUID_STRING(), '-', ''))
);


ALTER TABLE "governance"."gate_reviews"
    ADD COLUMN IF NOT EXISTS "project_id" VARCHAR;

ALTER TABLE "governance"."gate_reviews"
    ADD COLUMN IF NOT EXISTS "gate_code" VARCHAR;

ALTER TABLE "governance"."gate_reviews"
    ADD COLUMN IF NOT EXISTS "gate_name" VARCHAR;

ALTER TABLE "governance"."gate_reviews"
    ADD COLUMN IF NOT EXISTS "committee" VARCHAR;

ALTER TABLE "governance"."gate_reviews"
    ADD COLUMN IF NOT EXISTS "assigned_role" VARCHAR;

ALTER TABLE "governance"."gate_reviews"
    ADD COLUMN IF NOT EXISTS "status" VARCHAR;

ALTER TABLE "governance"."gate_reviews"
    ADD COLUMN IF NOT EXISTS "decision" VARCHAR;

ALTER TABLE "governance"."gate_reviews"
    ADD COLUMN IF NOT EXISTS "decision_by_id" VARCHAR;

ALTER TABLE "governance"."gate_reviews"
    ADD COLUMN IF NOT EXISTS "decision_at" TIMESTAMP_TZ;

ALTER TABLE "governance"."gate_reviews"
    ADD COLUMN IF NOT EXISTS "decision_notes" VARCHAR;

ALTER TABLE "governance"."gate_reviews"
    ADD COLUMN IF NOT EXISTS "checklist_items" VARIANT;

ALTER TABLE "governance"."gate_reviews"
    ADD COLUMN IF NOT EXISTS "submitted_at" TIMESTAMP_TZ;

ALTER TABLE "governance"."gate_reviews"
    ADD COLUMN IF NOT EXISTS "due_date" TIMESTAMP_TZ;

ALTER TABLE "governance"."gate_reviews"
    ADD COLUMN IF NOT EXISTS "priority" VARCHAR;

ALTER TABLE "governance"."gate_reviews"
    ADD COLUMN IF NOT EXISTS "version" NUMBER(19,0) NOT NULL DEFAULT 0;

ALTER TABLE "governance"."gate_reviews"
    ADD COLUMN IF NOT EXISTS "record_locator" VARCHAR;
UPDATE "governance"."gate_reviews"
    SET "record_locator" = ('rl_' || REPLACE(UUID_STRING(), '-', ''))
    WHERE "record_locator" IS NULL;
ALTER TABLE "governance"."gate_reviews"
    ALTER COLUMN "record_locator" SET NOT NULL;



CREATE TABLE IF NOT EXISTS "governance"."gate_submissions"
(
    "id" VARCHAR NOT NULL DEFAULT UUID_STRING() PRIMARY KEY
    ,"project_id" VARCHAR
    ,"stage" VARCHAR
    ,"status" VARCHAR
    ,"decision" VARCHAR
    ,"data" VARIANT
    ,"submitted_by" VARCHAR
    ,"submitted_at" TIMESTAMP_TZ
    ,"created_at" TIMESTAMP_TZ
    ,"updated_at" TIMESTAMP_TZ
    ,"version" NUMBER(19,0) NOT NULL DEFAULT 0
    ,"record_locator" VARCHAR NOT NULL DEFAULT ('rl_' || REPLACE(UUID_STRING(), '-', ''))
);


ALTER TABLE "governance"."gate_submissions"
    ADD COLUMN IF NOT EXISTS "project_id" VARCHAR;

ALTER TABLE "governance"."gate_submissions"
    ADD COLUMN IF NOT EXISTS "stage" VARCHAR;

ALTER TABLE "governance"."gate_submissions"
    ADD COLUMN IF NOT EXISTS "status" VARCHAR;

ALTER TABLE "governance"."gate_submissions"
    ADD COLUMN IF NOT EXISTS "decision" VARCHAR;

ALTER TABLE "governance"."gate_submissions"
    ADD COLUMN IF NOT EXISTS "data" VARIANT;

ALTER TABLE "governance"."gate_submissions"
    ADD COLUMN IF NOT EXISTS "submitted_by" VARCHAR;

ALTER TABLE "governance"."gate_submissions"
    ADD COLUMN IF NOT EXISTS "submitted_at" TIMESTAMP_TZ;

ALTER TABLE "governance"."gate_submissions"
    ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP_TZ;

ALTER TABLE "governance"."gate_submissions"
    ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP_TZ;

ALTER TABLE "governance"."gate_submissions"
    ADD COLUMN IF NOT EXISTS "version" NUMBER(19,0) NOT NULL DEFAULT 0;

ALTER TABLE "governance"."gate_submissions"
    ADD COLUMN IF NOT EXISTS "record_locator" VARCHAR;
UPDATE "governance"."gate_submissions"
    SET "record_locator" = ('rl_' || REPLACE(UUID_STRING(), '-', ''))
    WHERE "record_locator" IS NULL;
ALTER TABLE "governance"."gate_submissions"
    ALTER COLUMN "record_locator" SET NOT NULL;



CREATE TABLE IF NOT EXISTS "governance"."graph_subscriptions"
(
    "id" VARCHAR NOT NULL DEFAULT UUID_STRING() PRIMARY KEY
    ,"subscription_id" VARCHAR
    ,"resource" VARCHAR
    ,"notification_url" VARCHAR
    ,"client_state" VARCHAR
    ,"expiration_date_time" TIMESTAMP_TZ
    ,"created_at" TIMESTAMP_TZ
    ,"updated_at" TIMESTAMP_TZ
    ,"record_locator" VARCHAR NOT NULL DEFAULT ('rl_' || REPLACE(UUID_STRING(), '-', ''))
);


ALTER TABLE "governance"."graph_subscriptions"
    ADD COLUMN IF NOT EXISTS "subscription_id" VARCHAR;

ALTER TABLE "governance"."graph_subscriptions"
    ADD COLUMN IF NOT EXISTS "resource" VARCHAR;

ALTER TABLE "governance"."graph_subscriptions"
    ADD COLUMN IF NOT EXISTS "notification_url" VARCHAR;

ALTER TABLE "governance"."graph_subscriptions"
    ADD COLUMN IF NOT EXISTS "client_state" VARCHAR;

ALTER TABLE "governance"."graph_subscriptions"
    ADD COLUMN IF NOT EXISTS "expiration_date_time" TIMESTAMP_TZ;

ALTER TABLE "governance"."graph_subscriptions"
    ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP_TZ;

ALTER TABLE "governance"."graph_subscriptions"
    ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP_TZ;

ALTER TABLE "governance"."graph_subscriptions"
    ADD COLUMN IF NOT EXISTS "record_locator" VARCHAR;
UPDATE "governance"."graph_subscriptions"
    SET "record_locator" = ('rl_' || REPLACE(UUID_STRING(), '-', ''))
    WHERE "record_locator" IS NULL;
ALTER TABLE "governance"."graph_subscriptions"
    ALTER COLUMN "record_locator" SET NOT NULL;



CREATE TABLE IF NOT EXISTS "governance"."knowledge_chunks"
(
    "id" VARCHAR NOT NULL DEFAULT UUID_STRING() PRIMARY KEY
    ,"document_id" VARCHAR
    ,"chunk_text" VARCHAR
    ,"metadata" VARIANT
    ,"sequence_order" NUMBER(10,0)
    ,"record_locator" VARCHAR NOT NULL DEFAULT ('rl_' || REPLACE(UUID_STRING(), '-', ''))
);


ALTER TABLE "governance"."knowledge_chunks"
    ADD COLUMN IF NOT EXISTS "document_id" VARCHAR;

ALTER TABLE "governance"."knowledge_chunks"
    ADD COLUMN IF NOT EXISTS "chunk_text" VARCHAR;

ALTER TABLE "governance"."knowledge_chunks"
    ADD COLUMN IF NOT EXISTS "metadata" VARIANT;

ALTER TABLE "governance"."knowledge_chunks"
    ADD COLUMN IF NOT EXISTS "sequence_order" NUMBER(10,0);

ALTER TABLE "governance"."knowledge_chunks"
    ADD COLUMN IF NOT EXISTS "record_locator" VARCHAR;
UPDATE "governance"."knowledge_chunks"
    SET "record_locator" = ('rl_' || REPLACE(UUID_STRING(), '-', ''))
    WHERE "record_locator" IS NULL;
ALTER TABLE "governance"."knowledge_chunks"
    ALTER COLUMN "record_locator" SET NOT NULL;



CREATE TABLE IF NOT EXISTS "governance"."knowledge_documents"
(
    "id" VARCHAR NOT NULL DEFAULT UUID_STRING() PRIMARY KEY
    ,"title" VARCHAR
    ,"document_type" VARCHAR
    ,"source_url" VARCHAR
    ,"created_at" TIMESTAMP_TZ
    ,"record_locator" VARCHAR NOT NULL DEFAULT ('rl_' || REPLACE(UUID_STRING(), '-', ''))
);


ALTER TABLE "governance"."knowledge_documents"
    ADD COLUMN IF NOT EXISTS "title" VARCHAR;

ALTER TABLE "governance"."knowledge_documents"
    ADD COLUMN IF NOT EXISTS "document_type" VARCHAR;

ALTER TABLE "governance"."knowledge_documents"
    ADD COLUMN IF NOT EXISTS "source_url" VARCHAR;

ALTER TABLE "governance"."knowledge_documents"
    ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP_TZ;

ALTER TABLE "governance"."knowledge_documents"
    ADD COLUMN IF NOT EXISTS "record_locator" VARCHAR;
UPDATE "governance"."knowledge_documents"
    SET "record_locator" = ('rl_' || REPLACE(UUID_STRING(), '-', ''))
    WHERE "record_locator" IS NULL;
ALTER TABLE "governance"."knowledge_documents"
    ALTER COLUMN "record_locator" SET NOT NULL;



CREATE TABLE IF NOT EXISTS "governance"."meetings"
(
    "id" VARCHAR NOT NULL DEFAULT UUID_STRING() PRIMARY KEY
    ,"subject" VARCHAR
    ,"source" VARCHAR
    ,"status" VARCHAR
    ,"start_time" TIMESTAMP_TZ
    ,"end_time" TIMESTAMP_TZ
    ,"organizer_email" VARCHAR
    ,"graph_online_meeting_id" VARCHAR
    ,"graph_organizer_id" VARCHAR
    ,"graph_organizer_user_id" VARCHAR
    ,"graph_transcript_id" VARCHAR
    ,"graph_event_id" VARCHAR
    ,"join_url" VARCHAR
    ,"external_ref" VARCHAR
    ,"transcript_vtt" VARCHAR
    ,"transcript_text" VARCHAR
    ,"summary" VARCHAR
    ,"decisions" VARIANT
    ,"action_items" VARIANT
    ,"agenda_items" VARIANT
    ,"attendees" VARIANT
    ,"contains_process_flow" BOOLEAN
    ,"process_name" VARCHAR
    ,"bpmn_xml" VARCHAR
    ,"bpmn_status" VARCHAR
    ,"error_message" VARCHAR
    ,"created_at" TIMESTAMP_TZ
    ,"updated_at" TIMESTAMP_TZ
    ,"version" NUMBER(19,0) NOT NULL DEFAULT 0
    ,"record_locator" VARCHAR NOT NULL DEFAULT ('rl_' || REPLACE(UUID_STRING(), '-', ''))
);


ALTER TABLE "governance"."meetings"
    ADD COLUMN IF NOT EXISTS "subject" VARCHAR;

ALTER TABLE "governance"."meetings"
    ADD COLUMN IF NOT EXISTS "source" VARCHAR;

ALTER TABLE "governance"."meetings"
    ADD COLUMN IF NOT EXISTS "status" VARCHAR;

ALTER TABLE "governance"."meetings"
    ADD COLUMN IF NOT EXISTS "start_time" TIMESTAMP_TZ;

ALTER TABLE "governance"."meetings"
    ADD COLUMN IF NOT EXISTS "end_time" TIMESTAMP_TZ;

ALTER TABLE "governance"."meetings"
    ADD COLUMN IF NOT EXISTS "organizer_email" VARCHAR;

ALTER TABLE "governance"."meetings"
    ADD COLUMN IF NOT EXISTS "graph_online_meeting_id" VARCHAR;

ALTER TABLE "governance"."meetings"
    ADD COLUMN IF NOT EXISTS "graph_organizer_id" VARCHAR;

ALTER TABLE "governance"."meetings"
    ADD COLUMN IF NOT EXISTS "graph_organizer_user_id" VARCHAR;

ALTER TABLE "governance"."meetings"
    ADD COLUMN IF NOT EXISTS "graph_transcript_id" VARCHAR;

ALTER TABLE "governance"."meetings"
    ADD COLUMN IF NOT EXISTS "graph_event_id" VARCHAR;

ALTER TABLE "governance"."meetings"
    ADD COLUMN IF NOT EXISTS "join_url" VARCHAR;

ALTER TABLE "governance"."meetings"
    ADD COLUMN IF NOT EXISTS "external_ref" VARCHAR;

ALTER TABLE "governance"."meetings"
    ADD COLUMN IF NOT EXISTS "transcript_vtt" VARCHAR;

ALTER TABLE "governance"."meetings"
    ADD COLUMN IF NOT EXISTS "transcript_text" VARCHAR;

ALTER TABLE "governance"."meetings"
    ADD COLUMN IF NOT EXISTS "summary" VARCHAR;

ALTER TABLE "governance"."meetings"
    ADD COLUMN IF NOT EXISTS "decisions" VARIANT;

ALTER TABLE "governance"."meetings"
    ADD COLUMN IF NOT EXISTS "action_items" VARIANT;

ALTER TABLE "governance"."meetings"
    ADD COLUMN IF NOT EXISTS "agenda_items" VARIANT;

ALTER TABLE "governance"."meetings"
    ADD COLUMN IF NOT EXISTS "attendees" VARIANT;

ALTER TABLE "governance"."meetings"
    ADD COLUMN IF NOT EXISTS "contains_process_flow" BOOLEAN;

ALTER TABLE "governance"."meetings"
    ADD COLUMN IF NOT EXISTS "process_name" VARCHAR;

ALTER TABLE "governance"."meetings"
    ADD COLUMN IF NOT EXISTS "bpmn_xml" VARCHAR;

ALTER TABLE "governance"."meetings"
    ADD COLUMN IF NOT EXISTS "bpmn_status" VARCHAR;

ALTER TABLE "governance"."meetings"
    ADD COLUMN IF NOT EXISTS "error_message" VARCHAR;

ALTER TABLE "governance"."meetings"
    ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP_TZ;

ALTER TABLE "governance"."meetings"
    ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP_TZ;

ALTER TABLE "governance"."meetings"
    ADD COLUMN IF NOT EXISTS "version" NUMBER(19,0) NOT NULL DEFAULT 0;

ALTER TABLE "governance"."meetings"
    ADD COLUMN IF NOT EXISTS "record_locator" VARCHAR;
UPDATE "governance"."meetings"
    SET "record_locator" = ('rl_' || REPLACE(UUID_STRING(), '-', ''))
    WHERE "record_locator" IS NULL;
ALTER TABLE "governance"."meetings"
    ALTER COLUMN "record_locator" SET NOT NULL;



CREATE TABLE IF NOT EXISTS "governance"."notifications"
(
    "id" VARCHAR NOT NULL DEFAULT UUID_STRING() PRIMARY KEY
    ,"recipient_id" VARCHAR
    ,"project_id" VARCHAR
    ,"notification_type" VARCHAR
    ,"title" VARCHAR
    ,"message" VARCHAR
    ,"action_url" VARCHAR
    ,"is_read" BOOLEAN
    ,"created_at" TIMESTAMP_TZ
    ,"read_at" TIMESTAMP_TZ
    ,"record_locator" VARCHAR NOT NULL DEFAULT ('rl_' || REPLACE(UUID_STRING(), '-', ''))
);


ALTER TABLE "governance"."notifications"
    ADD COLUMN IF NOT EXISTS "recipient_id" VARCHAR;

ALTER TABLE "governance"."notifications"
    ADD COLUMN IF NOT EXISTS "project_id" VARCHAR;

ALTER TABLE "governance"."notifications"
    ADD COLUMN IF NOT EXISTS "notification_type" VARCHAR;

ALTER TABLE "governance"."notifications"
    ADD COLUMN IF NOT EXISTS "title" VARCHAR;

ALTER TABLE "governance"."notifications"
    ADD COLUMN IF NOT EXISTS "message" VARCHAR;

ALTER TABLE "governance"."notifications"
    ADD COLUMN IF NOT EXISTS "action_url" VARCHAR;

ALTER TABLE "governance"."notifications"
    ADD COLUMN IF NOT EXISTS "is_read" BOOLEAN;

ALTER TABLE "governance"."notifications"
    ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP_TZ;

ALTER TABLE "governance"."notifications"
    ADD COLUMN IF NOT EXISTS "read_at" TIMESTAMP_TZ;

ALTER TABLE "governance"."notifications"
    ADD COLUMN IF NOT EXISTS "record_locator" VARCHAR;
UPDATE "governance"."notifications"
    SET "record_locator" = ('rl_' || REPLACE(UUID_STRING(), '-', ''))
    WHERE "record_locator" IS NULL;
ALTER TABLE "governance"."notifications"
    ALTER COLUMN "record_locator" SET NOT NULL;



CREATE TABLE IF NOT EXISTS "governance"."projects"
(
    "id" VARCHAR NOT NULL DEFAULT UUID_STRING() PRIMARY KEY
    ,"project_number" VARCHAR
    ,"project_name" VARCHAR
    ,"business_unit" VARCHAR
    ,"department" VARCHAR
    ,"manager_id" VARCHAR
    ,"sponsor_name" VARCHAR
    ,"sponsor_email" VARCHAR
    ,"description" VARCHAR
    ,"problem_statement" VARCHAR
    ,"business_value" VARCHAR
    ,"strategic_alignment" VARCHAR
    ,"requestor_name" VARCHAR
    ,"request_type" VARCHAR
    ,"desired_outcome" VARCHAR
    ,"what_do_you_do_today" VARCHAR
    ,"what_transpires_if_nothing" VARCHAR
    ,"notes" VARCHAR
    ,"budget_estimated" FLOAT
    ,"budget_approved" FLOAT
    ,"budget_type" VARCHAR
    ,"requested_start_date" TIMESTAMP_TZ
    ,"requested_end_date" TIMESTAMP_TZ
    ,"actual_start_date" TIMESTAMP_TZ
    ,"actual_end_date" TIMESTAMP_TZ
    ,"priority" VARCHAR
    ,"risk_level" VARCHAR
    ,"status" VARCHAR
    ,"it_involvement" BOOLEAN
    ,"vendor_required" BOOLEAN
    ,"has_phi_data" BOOLEAN
    ,"is_clinical" BOOLEAN
    ,"is_hipaa_applicable" BOOLEAN
    ,"smartsheet_row_id" VARCHAR
    ,"smartsheet_sheet_url" VARCHAR
    ,"jira_ticket_id" VARCHAR
    ,"duplicate_of_id" VARCHAR
    ,"is_duplicate" BOOLEAN
    ,"ai_extracted_data" VARIANT
    ,"current_stage" VARCHAR
    ,"current_status" VARCHAR
    ,"current_owner_role" VARCHAR
    ,"last_stage_completed" VARCHAR
    ,"workflow_status" VARCHAR
    ,"submitted_at" TIMESTAMP_TZ
    ,"created_at" TIMESTAMP_TZ
    ,"updated_at" TIMESTAMP_TZ
    ,"archived_at" TIMESTAMP_TZ
    ,"version" NUMBER(19,0) NOT NULL DEFAULT 0
    ,"record_locator" VARCHAR NOT NULL DEFAULT ('rl_' || REPLACE(UUID_STRING(), '-', ''))
);


ALTER TABLE "governance"."projects"
    ADD COLUMN IF NOT EXISTS "project_number" VARCHAR;

ALTER TABLE "governance"."projects"
    ADD COLUMN IF NOT EXISTS "project_name" VARCHAR;

ALTER TABLE "governance"."projects"
    ADD COLUMN IF NOT EXISTS "business_unit" VARCHAR;

ALTER TABLE "governance"."projects"
    ADD COLUMN IF NOT EXISTS "department" VARCHAR;

ALTER TABLE "governance"."projects"
    ADD COLUMN IF NOT EXISTS "manager_id" VARCHAR;

ALTER TABLE "governance"."projects"
    ADD COLUMN IF NOT EXISTS "sponsor_name" VARCHAR;

ALTER TABLE "governance"."projects"
    ADD COLUMN IF NOT EXISTS "sponsor_email" VARCHAR;

ALTER TABLE "governance"."projects"
    ADD COLUMN IF NOT EXISTS "description" VARCHAR;

ALTER TABLE "governance"."projects"
    ADD COLUMN IF NOT EXISTS "problem_statement" VARCHAR;

ALTER TABLE "governance"."projects"
    ADD COLUMN IF NOT EXISTS "business_value" VARCHAR;

ALTER TABLE "governance"."projects"
    ADD COLUMN IF NOT EXISTS "strategic_alignment" VARCHAR;

ALTER TABLE "governance"."projects"
    ADD COLUMN IF NOT EXISTS "requestor_name" VARCHAR;

ALTER TABLE "governance"."projects"
    ADD COLUMN IF NOT EXISTS "request_type" VARCHAR;

ALTER TABLE "governance"."projects"
    ADD COLUMN IF NOT EXISTS "desired_outcome" VARCHAR;

ALTER TABLE "governance"."projects"
    ADD COLUMN IF NOT EXISTS "what_do_you_do_today" VARCHAR;

ALTER TABLE "governance"."projects"
    ADD COLUMN IF NOT EXISTS "what_transpires_if_nothing" VARCHAR;

ALTER TABLE "governance"."projects"
    ADD COLUMN IF NOT EXISTS "notes" VARCHAR;

ALTER TABLE "governance"."projects"
    ADD COLUMN IF NOT EXISTS "budget_estimated" FLOAT;

ALTER TABLE "governance"."projects"
    ADD COLUMN IF NOT EXISTS "budget_approved" FLOAT;

ALTER TABLE "governance"."projects"
    ADD COLUMN IF NOT EXISTS "budget_type" VARCHAR;

ALTER TABLE "governance"."projects"
    ADD COLUMN IF NOT EXISTS "requested_start_date" TIMESTAMP_TZ;

ALTER TABLE "governance"."projects"
    ADD COLUMN IF NOT EXISTS "requested_end_date" TIMESTAMP_TZ;

ALTER TABLE "governance"."projects"
    ADD COLUMN IF NOT EXISTS "actual_start_date" TIMESTAMP_TZ;

ALTER TABLE "governance"."projects"
    ADD COLUMN IF NOT EXISTS "actual_end_date" TIMESTAMP_TZ;

ALTER TABLE "governance"."projects"
    ADD COLUMN IF NOT EXISTS "priority" VARCHAR;

ALTER TABLE "governance"."projects"
    ADD COLUMN IF NOT EXISTS "risk_level" VARCHAR;

ALTER TABLE "governance"."projects"
    ADD COLUMN IF NOT EXISTS "status" VARCHAR;

ALTER TABLE "governance"."projects"
    ADD COLUMN IF NOT EXISTS "it_involvement" BOOLEAN;

ALTER TABLE "governance"."projects"
    ADD COLUMN IF NOT EXISTS "vendor_required" BOOLEAN;

ALTER TABLE "governance"."projects"
    ADD COLUMN IF NOT EXISTS "has_phi_data" BOOLEAN;

ALTER TABLE "governance"."projects"
    ADD COLUMN IF NOT EXISTS "is_clinical" BOOLEAN;

ALTER TABLE "governance"."projects"
    ADD COLUMN IF NOT EXISTS "is_hipaa_applicable" BOOLEAN;

ALTER TABLE "governance"."projects"
    ADD COLUMN IF NOT EXISTS "smartsheet_row_id" VARCHAR;

ALTER TABLE "governance"."projects"
    ADD COLUMN IF NOT EXISTS "smartsheet_sheet_url" VARCHAR;

ALTER TABLE "governance"."projects"
    ADD COLUMN IF NOT EXISTS "jira_ticket_id" VARCHAR;

ALTER TABLE "governance"."projects"
    ADD COLUMN IF NOT EXISTS "duplicate_of_id" VARCHAR;

ALTER TABLE "governance"."projects"
    ADD COLUMN IF NOT EXISTS "is_duplicate" BOOLEAN;

ALTER TABLE "governance"."projects"
    ADD COLUMN IF NOT EXISTS "ai_extracted_data" VARIANT;

ALTER TABLE "governance"."projects"
    ADD COLUMN IF NOT EXISTS "current_stage" VARCHAR;

ALTER TABLE "governance"."projects"
    ADD COLUMN IF NOT EXISTS "current_status" VARCHAR;

ALTER TABLE "governance"."projects"
    ADD COLUMN IF NOT EXISTS "current_owner_role" VARCHAR;

ALTER TABLE "governance"."projects"
    ADD COLUMN IF NOT EXISTS "last_stage_completed" VARCHAR;

ALTER TABLE "governance"."projects"
    ADD COLUMN IF NOT EXISTS "workflow_status" VARCHAR;

ALTER TABLE "governance"."projects"
    ADD COLUMN IF NOT EXISTS "submitted_at" TIMESTAMP_TZ;

ALTER TABLE "governance"."projects"
    ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP_TZ;

ALTER TABLE "governance"."projects"
    ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP_TZ;

ALTER TABLE "governance"."projects"
    ADD COLUMN IF NOT EXISTS "archived_at" TIMESTAMP_TZ;

ALTER TABLE "governance"."projects"
    ADD COLUMN IF NOT EXISTS "version" NUMBER(19,0) NOT NULL DEFAULT 0;

ALTER TABLE "governance"."projects"
    ADD COLUMN IF NOT EXISTS "record_locator" VARCHAR;
UPDATE "governance"."projects"
    SET "record_locator" = ('rl_' || REPLACE(UUID_STRING(), '-', ''))
    WHERE "record_locator" IS NULL;
ALTER TABLE "governance"."projects"
    ALTER COLUMN "record_locator" SET NOT NULL;



CREATE TABLE IF NOT EXISTS "governance"."project_approvals"
(
    "id" VARCHAR NOT NULL DEFAULT UUID_STRING() PRIMARY KEY
    ,"project_id" VARCHAR
    ,"approval_stage" VARCHAR
    ,"assigned_role" VARCHAR
    ,"assigned_user_id" VARCHAR
    ,"status" VARCHAR
    ,"decision" VARCHAR
    ,"comments" VARCHAR
    ,"approved_by" VARCHAR
    ,"approved_at" TIMESTAMP_TZ
    ,"sequence_order" NUMBER(10,0)
    ,"notification_sent" BOOLEAN
    ,"created_at" TIMESTAMP_TZ
    ,"updated_at" TIMESTAMP_TZ
    ,"version" NUMBER(19,0) NOT NULL DEFAULT 0
    ,"record_locator" VARCHAR NOT NULL DEFAULT ('rl_' || REPLACE(UUID_STRING(), '-', ''))
);


ALTER TABLE "governance"."project_approvals"
    ADD COLUMN IF NOT EXISTS "project_id" VARCHAR;

ALTER TABLE "governance"."project_approvals"
    ADD COLUMN IF NOT EXISTS "approval_stage" VARCHAR;

ALTER TABLE "governance"."project_approvals"
    ADD COLUMN IF NOT EXISTS "assigned_role" VARCHAR;

ALTER TABLE "governance"."project_approvals"
    ADD COLUMN IF NOT EXISTS "assigned_user_id" VARCHAR;

ALTER TABLE "governance"."project_approvals"
    ADD COLUMN IF NOT EXISTS "status" VARCHAR;

ALTER TABLE "governance"."project_approvals"
    ADD COLUMN IF NOT EXISTS "decision" VARCHAR;

ALTER TABLE "governance"."project_approvals"
    ADD COLUMN IF NOT EXISTS "comments" VARCHAR;

ALTER TABLE "governance"."project_approvals"
    ADD COLUMN IF NOT EXISTS "approved_by" VARCHAR;

ALTER TABLE "governance"."project_approvals"
    ADD COLUMN IF NOT EXISTS "approved_at" TIMESTAMP_TZ;

ALTER TABLE "governance"."project_approvals"
    ADD COLUMN IF NOT EXISTS "sequence_order" NUMBER(10,0);

ALTER TABLE "governance"."project_approvals"
    ADD COLUMN IF NOT EXISTS "notification_sent" BOOLEAN;

ALTER TABLE "governance"."project_approvals"
    ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP_TZ;

ALTER TABLE "governance"."project_approvals"
    ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP_TZ;

ALTER TABLE "governance"."project_approvals"
    ADD COLUMN IF NOT EXISTS "version" NUMBER(19,0) NOT NULL DEFAULT 0;

ALTER TABLE "governance"."project_approvals"
    ADD COLUMN IF NOT EXISTS "record_locator" VARCHAR;
UPDATE "governance"."project_approvals"
    SET "record_locator" = ('rl_' || REPLACE(UUID_STRING(), '-', ''))
    WHERE "record_locator" IS NULL;
ALTER TABLE "governance"."project_approvals"
    ALTER COLUMN "record_locator" SET NOT NULL;



CREATE TABLE IF NOT EXISTS "governance"."project_fields"
(
    "id" VARCHAR NOT NULL DEFAULT UUID_STRING() PRIMARY KEY
    ,"project_id" VARCHAR
    ,"field_name" VARCHAR
    ,"field_value" VARIANT
    ,"is_ai_suggested" BOOLEAN
    ,"ai_confidence" FLOAT
    ,"ai_source_document" VARCHAR
    ,"ai_extracted_text" VARCHAR
    ,"updated_at" TIMESTAMP_TZ
    ,"updated_by_id" VARCHAR
    ,"record_locator" VARCHAR NOT NULL DEFAULT ('rl_' || REPLACE(UUID_STRING(), '-', ''))
);


ALTER TABLE "governance"."project_fields"
    ADD COLUMN IF NOT EXISTS "project_id" VARCHAR;

ALTER TABLE "governance"."project_fields"
    ADD COLUMN IF NOT EXISTS "field_name" VARCHAR;

ALTER TABLE "governance"."project_fields"
    ADD COLUMN IF NOT EXISTS "field_value" VARIANT;

ALTER TABLE "governance"."project_fields"
    ADD COLUMN IF NOT EXISTS "is_ai_suggested" BOOLEAN;

ALTER TABLE "governance"."project_fields"
    ADD COLUMN IF NOT EXISTS "ai_confidence" FLOAT;

ALTER TABLE "governance"."project_fields"
    ADD COLUMN IF NOT EXISTS "ai_source_document" VARCHAR;

ALTER TABLE "governance"."project_fields"
    ADD COLUMN IF NOT EXISTS "ai_extracted_text" VARCHAR;

ALTER TABLE "governance"."project_fields"
    ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP_TZ;

ALTER TABLE "governance"."project_fields"
    ADD COLUMN IF NOT EXISTS "updated_by_id" VARCHAR;

ALTER TABLE "governance"."project_fields"
    ADD COLUMN IF NOT EXISTS "record_locator" VARCHAR;
UPDATE "governance"."project_fields"
    SET "record_locator" = ('rl_' || REPLACE(UUID_STRING(), '-', ''))
    WHERE "record_locator" IS NULL;
ALTER TABLE "governance"."project_fields"
    ALTER COLUMN "record_locator" SET NOT NULL;



CREATE TABLE IF NOT EXISTS "governance"."project_stakeholders"
(
    "id" VARCHAR NOT NULL DEFAULT UUID_STRING() PRIMARY KEY
    ,"project_id" VARCHAR
    ,"user_id" VARCHAR
    ,"role" VARCHAR
    ,"added_at" TIMESTAMP_TZ
    ,"record_locator" VARCHAR NOT NULL DEFAULT ('rl_' || REPLACE(UUID_STRING(), '-', ''))
);


ALTER TABLE "governance"."project_stakeholders"
    ADD COLUMN IF NOT EXISTS "project_id" VARCHAR;

ALTER TABLE "governance"."project_stakeholders"
    ADD COLUMN IF NOT EXISTS "user_id" VARCHAR;

ALTER TABLE "governance"."project_stakeholders"
    ADD COLUMN IF NOT EXISTS "role" VARCHAR;

ALTER TABLE "governance"."project_stakeholders"
    ADD COLUMN IF NOT EXISTS "added_at" TIMESTAMP_TZ;

ALTER TABLE "governance"."project_stakeholders"
    ADD COLUMN IF NOT EXISTS "record_locator" VARCHAR;
UPDATE "governance"."project_stakeholders"
    SET "record_locator" = ('rl_' || REPLACE(UUID_STRING(), '-', ''))
    WHERE "record_locator" IS NULL;
ALTER TABLE "governance"."project_stakeholders"
    ALTER COLUMN "record_locator" SET NOT NULL;



CREATE TABLE IF NOT EXISTS "governance"."risk_items"
(
    "id" VARCHAR NOT NULL DEFAULT UUID_STRING() PRIMARY KEY
    ,"project_id" VARCHAR
    ,"risk_title" VARCHAR
    ,"risk_description" VARCHAR
    ,"risk_category" VARCHAR
    ,"severity" VARCHAR
    ,"probability" VARCHAR
    ,"impact" VARCHAR
    ,"mitigation_plan" VARCHAR
    ,"owner_id" VARCHAR
    ,"status" VARCHAR
    ,"identified_at" TIMESTAMP_TZ
    ,"resolved_at" TIMESTAMP_TZ
    ,"record_locator" VARCHAR NOT NULL DEFAULT ('rl_' || REPLACE(UUID_STRING(), '-', ''))
);


ALTER TABLE "governance"."risk_items"
    ADD COLUMN IF NOT EXISTS "project_id" VARCHAR;

ALTER TABLE "governance"."risk_items"
    ADD COLUMN IF NOT EXISTS "risk_title" VARCHAR;

ALTER TABLE "governance"."risk_items"
    ADD COLUMN IF NOT EXISTS "risk_description" VARCHAR;

ALTER TABLE "governance"."risk_items"
    ADD COLUMN IF NOT EXISTS "risk_category" VARCHAR;

ALTER TABLE "governance"."risk_items"
    ADD COLUMN IF NOT EXISTS "severity" VARCHAR;

ALTER TABLE "governance"."risk_items"
    ADD COLUMN IF NOT EXISTS "probability" VARCHAR;

ALTER TABLE "governance"."risk_items"
    ADD COLUMN IF NOT EXISTS "impact" VARCHAR;

ALTER TABLE "governance"."risk_items"
    ADD COLUMN IF NOT EXISTS "mitigation_plan" VARCHAR;

ALTER TABLE "governance"."risk_items"
    ADD COLUMN IF NOT EXISTS "owner_id" VARCHAR;

ALTER TABLE "governance"."risk_items"
    ADD COLUMN IF NOT EXISTS "status" VARCHAR;

ALTER TABLE "governance"."risk_items"
    ADD COLUMN IF NOT EXISTS "identified_at" TIMESTAMP_TZ;

ALTER TABLE "governance"."risk_items"
    ADD COLUMN IF NOT EXISTS "resolved_at" TIMESTAMP_TZ;

ALTER TABLE "governance"."risk_items"
    ADD COLUMN IF NOT EXISTS "record_locator" VARCHAR;
UPDATE "governance"."risk_items"
    SET "record_locator" = ('rl_' || REPLACE(UUID_STRING(), '-', ''))
    WHERE "record_locator" IS NULL;
ALTER TABLE "governance"."risk_items"
    ALTER COLUMN "record_locator" SET NOT NULL;



CREATE TABLE IF NOT EXISTS "governance"."task_assignments"
(
    "id" VARCHAR NOT NULL DEFAULT UUID_STRING() PRIMARY KEY
    ,"task_id" VARCHAR
    ,"assignee_id" VARCHAR
    ,"assigned_at" TIMESTAMP_TZ
    ,"assigned_by_id" VARCHAR
    ,"accepted_at" TIMESTAMP_TZ
    ,"completed_at" TIMESTAMP_TZ
    ,"notes" VARCHAR
    ,"record_locator" VARCHAR NOT NULL DEFAULT ('rl_' || REPLACE(UUID_STRING(), '-', ''))
);


ALTER TABLE "governance"."task_assignments"
    ADD COLUMN IF NOT EXISTS "task_id" VARCHAR;

ALTER TABLE "governance"."task_assignments"
    ADD COLUMN IF NOT EXISTS "assignee_id" VARCHAR;

ALTER TABLE "governance"."task_assignments"
    ADD COLUMN IF NOT EXISTS "assigned_at" TIMESTAMP_TZ;

ALTER TABLE "governance"."task_assignments"
    ADD COLUMN IF NOT EXISTS "assigned_by_id" VARCHAR;

ALTER TABLE "governance"."task_assignments"
    ADD COLUMN IF NOT EXISTS "accepted_at" TIMESTAMP_TZ;

ALTER TABLE "governance"."task_assignments"
    ADD COLUMN IF NOT EXISTS "completed_at" TIMESTAMP_TZ;

ALTER TABLE "governance"."task_assignments"
    ADD COLUMN IF NOT EXISTS "notes" VARCHAR;

ALTER TABLE "governance"."task_assignments"
    ADD COLUMN IF NOT EXISTS "record_locator" VARCHAR;
UPDATE "governance"."task_assignments"
    SET "record_locator" = ('rl_' || REPLACE(UUID_STRING(), '-', ''))
    WHERE "record_locator" IS NULL;
ALTER TABLE "governance"."task_assignments"
    ALTER COLUMN "record_locator" SET NOT NULL;



CREATE TABLE IF NOT EXISTS "governance"."users"
(
    "id" VARCHAR NOT NULL DEFAULT UUID_STRING() PRIMARY KEY
    ,"email" VARCHAR
    ,"username" VARCHAR
    ,"full_name" VARCHAR
    ,"hashed_password" VARCHAR
    ,"role" VARCHAR
    ,"department" VARCHAR
    ,"job_title" VARCHAR
    ,"phone" VARCHAR
    ,"avatar_url" VARCHAR
    ,"is_active" BOOLEAN
    ,"is_verified" BOOLEAN
    ,"last_login" TIMESTAMP_TZ
    ,"created_at" TIMESTAMP_TZ
    ,"updated_at" TIMESTAMP_TZ
    ,"version" NUMBER(19,0) NOT NULL DEFAULT 0
    ,"record_locator" VARCHAR NOT NULL DEFAULT ('rl_' || REPLACE(UUID_STRING(), '-', ''))
);


ALTER TABLE "governance"."users"
    ADD COLUMN IF NOT EXISTS "email" VARCHAR;

ALTER TABLE "governance"."users"
    ADD COLUMN IF NOT EXISTS "username" VARCHAR;

ALTER TABLE "governance"."users"
    ADD COLUMN IF NOT EXISTS "full_name" VARCHAR;

ALTER TABLE "governance"."users"
    ADD COLUMN IF NOT EXISTS "hashed_password" VARCHAR;

ALTER TABLE "governance"."users"
    ADD COLUMN IF NOT EXISTS "role" VARCHAR;

ALTER TABLE "governance"."users"
    ADD COLUMN IF NOT EXISTS "department" VARCHAR;

ALTER TABLE "governance"."users"
    ADD COLUMN IF NOT EXISTS "job_title" VARCHAR;

ALTER TABLE "governance"."users"
    ADD COLUMN IF NOT EXISTS "phone" VARCHAR;

ALTER TABLE "governance"."users"
    ADD COLUMN IF NOT EXISTS "avatar_url" VARCHAR;

ALTER TABLE "governance"."users"
    ADD COLUMN IF NOT EXISTS "is_active" BOOLEAN;

ALTER TABLE "governance"."users"
    ADD COLUMN IF NOT EXISTS "is_verified" BOOLEAN;

ALTER TABLE "governance"."users"
    ADD COLUMN IF NOT EXISTS "last_login" TIMESTAMP_TZ;

ALTER TABLE "governance"."users"
    ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP_TZ;

ALTER TABLE "governance"."users"
    ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP_TZ;

ALTER TABLE "governance"."users"
    ADD COLUMN IF NOT EXISTS "version" NUMBER(19,0) NOT NULL DEFAULT 0;

ALTER TABLE "governance"."users"
    ADD COLUMN IF NOT EXISTS "record_locator" VARCHAR;
UPDATE "governance"."users"
    SET "record_locator" = ('rl_' || REPLACE(UUID_STRING(), '-', ''))
    WHERE "record_locator" IS NULL;
ALTER TABLE "governance"."users"
    ALTER COLUMN "record_locator" SET NOT NULL;



CREATE TABLE IF NOT EXISTS "governance"."workflow_definitions"
(
    "id" VARCHAR NOT NULL DEFAULT UUID_STRING() PRIMARY KEY
    ,"name" VARCHAR
    ,"description" VARCHAR
    ,"definition_version" NUMBER(10,0)
    ,"is_active" BOOLEAN
    ,"created_at" TIMESTAMP_TZ
    ,"version" NUMBER(19,0) NOT NULL DEFAULT 0
    ,"record_locator" VARCHAR NOT NULL DEFAULT ('rl_' || REPLACE(UUID_STRING(), '-', ''))
);


ALTER TABLE "governance"."workflow_definitions"
    ADD COLUMN IF NOT EXISTS "name" VARCHAR;

ALTER TABLE "governance"."workflow_definitions"
    ADD COLUMN IF NOT EXISTS "description" VARCHAR;

ALTER TABLE "governance"."workflow_definitions"
    ADD COLUMN IF NOT EXISTS "definition_version" NUMBER(10,0);

ALTER TABLE "governance"."workflow_definitions"
    ADD COLUMN IF NOT EXISTS "is_active" BOOLEAN;

ALTER TABLE "governance"."workflow_definitions"
    ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP_TZ;

ALTER TABLE "governance"."workflow_definitions"
    ADD COLUMN IF NOT EXISTS "version" NUMBER(19,0) NOT NULL DEFAULT 0;

ALTER TABLE "governance"."workflow_definitions"
    ADD COLUMN IF NOT EXISTS "record_locator" VARCHAR;
UPDATE "governance"."workflow_definitions"
    SET "record_locator" = ('rl_' || REPLACE(UUID_STRING(), '-', ''))
    WHERE "record_locator" IS NULL;
ALTER TABLE "governance"."workflow_definitions"
    ALTER COLUMN "record_locator" SET NOT NULL;



CREATE TABLE IF NOT EXISTS "governance"."workflow_instances"
(
    "id" VARCHAR NOT NULL DEFAULT UUID_STRING() PRIMARY KEY
    ,"project_id" VARCHAR
    ,"definition_id" VARCHAR
    ,"current_stage_id" VARCHAR
    ,"status" VARCHAR
    ,"started_at" TIMESTAMP_TZ
    ,"completed_at" TIMESTAMP_TZ
    ,"record_locator" VARCHAR NOT NULL DEFAULT ('rl_' || REPLACE(UUID_STRING(), '-', ''))
);


ALTER TABLE "governance"."workflow_instances"
    ADD COLUMN IF NOT EXISTS "project_id" VARCHAR;

ALTER TABLE "governance"."workflow_instances"
    ADD COLUMN IF NOT EXISTS "definition_id" VARCHAR;

ALTER TABLE "governance"."workflow_instances"
    ADD COLUMN IF NOT EXISTS "current_stage_id" VARCHAR;

ALTER TABLE "governance"."workflow_instances"
    ADD COLUMN IF NOT EXISTS "status" VARCHAR;

ALTER TABLE "governance"."workflow_instances"
    ADD COLUMN IF NOT EXISTS "started_at" TIMESTAMP_TZ;

ALTER TABLE "governance"."workflow_instances"
    ADD COLUMN IF NOT EXISTS "completed_at" TIMESTAMP_TZ;

ALTER TABLE "governance"."workflow_instances"
    ADD COLUMN IF NOT EXISTS "record_locator" VARCHAR;
UPDATE "governance"."workflow_instances"
    SET "record_locator" = ('rl_' || REPLACE(UUID_STRING(), '-', ''))
    WHERE "record_locator" IS NULL;
ALTER TABLE "governance"."workflow_instances"
    ALTER COLUMN "record_locator" SET NOT NULL;



CREATE TABLE IF NOT EXISTS "governance"."workflow_stages"
(
    "id" VARCHAR NOT NULL DEFAULT UUID_STRING() PRIMARY KEY
    ,"workflow_instance_id" VARCHAR
    ,"stage_definition_id" VARCHAR
    ,"stage_name" VARCHAR
    ,"stage_code" VARCHAR
    ,"sequence_order" NUMBER(10,0)
    ,"status" VARCHAR
    ,"started_at" TIMESTAMP_TZ
    ,"completed_at" TIMESTAMP_TZ
    ,"due_date" TIMESTAMP_TZ
    ,"notes" VARCHAR
    ,"version" NUMBER(19,0) NOT NULL DEFAULT 0
    ,"record_locator" VARCHAR NOT NULL DEFAULT ('rl_' || REPLACE(UUID_STRING(), '-', ''))
);


ALTER TABLE "governance"."workflow_stages"
    ADD COLUMN IF NOT EXISTS "workflow_instance_id" VARCHAR;

ALTER TABLE "governance"."workflow_stages"
    ADD COLUMN IF NOT EXISTS "stage_definition_id" VARCHAR;

ALTER TABLE "governance"."workflow_stages"
    ADD COLUMN IF NOT EXISTS "stage_name" VARCHAR;

ALTER TABLE "governance"."workflow_stages"
    ADD COLUMN IF NOT EXISTS "stage_code" VARCHAR;

ALTER TABLE "governance"."workflow_stages"
    ADD COLUMN IF NOT EXISTS "sequence_order" NUMBER(10,0);

ALTER TABLE "governance"."workflow_stages"
    ADD COLUMN IF NOT EXISTS "status" VARCHAR;

ALTER TABLE "governance"."workflow_stages"
    ADD COLUMN IF NOT EXISTS "started_at" TIMESTAMP_TZ;

ALTER TABLE "governance"."workflow_stages"
    ADD COLUMN IF NOT EXISTS "completed_at" TIMESTAMP_TZ;

ALTER TABLE "governance"."workflow_stages"
    ADD COLUMN IF NOT EXISTS "due_date" TIMESTAMP_TZ;

ALTER TABLE "governance"."workflow_stages"
    ADD COLUMN IF NOT EXISTS "notes" VARCHAR;

ALTER TABLE "governance"."workflow_stages"
    ADD COLUMN IF NOT EXISTS "version" NUMBER(19,0) NOT NULL DEFAULT 0;

ALTER TABLE "governance"."workflow_stages"
    ADD COLUMN IF NOT EXISTS "record_locator" VARCHAR;
UPDATE "governance"."workflow_stages"
    SET "record_locator" = ('rl_' || REPLACE(UUID_STRING(), '-', ''))
    WHERE "record_locator" IS NULL;
ALTER TABLE "governance"."workflow_stages"
    ALTER COLUMN "record_locator" SET NOT NULL;



CREATE TABLE IF NOT EXISTS "governance"."workflow_stage_definitions"
(
    "id" VARCHAR NOT NULL DEFAULT UUID_STRING() PRIMARY KEY
    ,"workflow_id" VARCHAR
    ,"stage_name" VARCHAR
    ,"stage_code" VARCHAR
    ,"sequence_order" NUMBER(10,0)
    ,"description" VARCHAR
    ,"phase_name" VARCHAR
    ,"assigned_roles" VARIANT
    ,"prerequisites" VARIANT
    ,"conditions" VARIANT
    ,"parallel_execution" BOOLEAN
    ,"auto_advance" BOOLEAN
    ,"sla_days" NUMBER(10,0)
    ,"checklist_template" VARIANT
    ,"record_locator" VARCHAR NOT NULL DEFAULT ('rl_' || REPLACE(UUID_STRING(), '-', ''))
);


ALTER TABLE "governance"."workflow_stage_definitions"
    ADD COLUMN IF NOT EXISTS "workflow_id" VARCHAR;

ALTER TABLE "governance"."workflow_stage_definitions"
    ADD COLUMN IF NOT EXISTS "stage_name" VARCHAR;

ALTER TABLE "governance"."workflow_stage_definitions"
    ADD COLUMN IF NOT EXISTS "stage_code" VARCHAR;

ALTER TABLE "governance"."workflow_stage_definitions"
    ADD COLUMN IF NOT EXISTS "sequence_order" NUMBER(10,0);

ALTER TABLE "governance"."workflow_stage_definitions"
    ADD COLUMN IF NOT EXISTS "description" VARCHAR;

ALTER TABLE "governance"."workflow_stage_definitions"
    ADD COLUMN IF NOT EXISTS "phase_name" VARCHAR;

ALTER TABLE "governance"."workflow_stage_definitions"
    ADD COLUMN IF NOT EXISTS "assigned_roles" VARIANT;

ALTER TABLE "governance"."workflow_stage_definitions"
    ADD COLUMN IF NOT EXISTS "prerequisites" VARIANT;

ALTER TABLE "governance"."workflow_stage_definitions"
    ADD COLUMN IF NOT EXISTS "conditions" VARIANT;

ALTER TABLE "governance"."workflow_stage_definitions"
    ADD COLUMN IF NOT EXISTS "parallel_execution" BOOLEAN;

ALTER TABLE "governance"."workflow_stage_definitions"
    ADD COLUMN IF NOT EXISTS "auto_advance" BOOLEAN;

ALTER TABLE "governance"."workflow_stage_definitions"
    ADD COLUMN IF NOT EXISTS "sla_days" NUMBER(10,0);

ALTER TABLE "governance"."workflow_stage_definitions"
    ADD COLUMN IF NOT EXISTS "checklist_template" VARIANT;

ALTER TABLE "governance"."workflow_stage_definitions"
    ADD COLUMN IF NOT EXISTS "record_locator" VARCHAR;
UPDATE "governance"."workflow_stage_definitions"
    SET "record_locator" = ('rl_' || REPLACE(UUID_STRING(), '-', ''))
    WHERE "record_locator" IS NULL;
ALTER TABLE "governance"."workflow_stage_definitions"
    ALTER COLUMN "record_locator" SET NOT NULL;



CREATE TABLE IF NOT EXISTS "governance"."workflow_tasks"
(
    "id" VARCHAR NOT NULL DEFAULT UUID_STRING() PRIMARY KEY
    ,"stage_id" VARCHAR
    ,"task_name" VARCHAR
    ,"task_description" VARCHAR
    ,"task_type" VARCHAR
    ,"assigned_role" VARCHAR
    ,"status" VARCHAR
    ,"is_required" BOOLEAN
    ,"sequence_order" NUMBER(10,0)
    ,"due_date" TIMESTAMP_TZ
    ,"completed_at" TIMESTAMP_TZ
    ,"notes" VARCHAR
    ,"metadata" VARIANT
    ,"record_locator" VARCHAR NOT NULL DEFAULT ('rl_' || REPLACE(UUID_STRING(), '-', ''))
);


ALTER TABLE "governance"."workflow_tasks"
    ADD COLUMN IF NOT EXISTS "stage_id" VARCHAR;

ALTER TABLE "governance"."workflow_tasks"
    ADD COLUMN IF NOT EXISTS "task_name" VARCHAR;

ALTER TABLE "governance"."workflow_tasks"
    ADD COLUMN IF NOT EXISTS "task_description" VARCHAR;

ALTER TABLE "governance"."workflow_tasks"
    ADD COLUMN IF NOT EXISTS "task_type" VARCHAR;

ALTER TABLE "governance"."workflow_tasks"
    ADD COLUMN IF NOT EXISTS "assigned_role" VARCHAR;

ALTER TABLE "governance"."workflow_tasks"
    ADD COLUMN IF NOT EXISTS "status" VARCHAR;

ALTER TABLE "governance"."workflow_tasks"
    ADD COLUMN IF NOT EXISTS "is_required" BOOLEAN;

ALTER TABLE "governance"."workflow_tasks"
    ADD COLUMN IF NOT EXISTS "sequence_order" NUMBER(10,0);

ALTER TABLE "governance"."workflow_tasks"
    ADD COLUMN IF NOT EXISTS "due_date" TIMESTAMP_TZ;

ALTER TABLE "governance"."workflow_tasks"
    ADD COLUMN IF NOT EXISTS "completed_at" TIMESTAMP_TZ;

ALTER TABLE "governance"."workflow_tasks"
    ADD COLUMN IF NOT EXISTS "notes" VARCHAR;

ALTER TABLE "governance"."workflow_tasks"
    ADD COLUMN IF NOT EXISTS "metadata" VARIANT;

ALTER TABLE "governance"."workflow_tasks"
    ADD COLUMN IF NOT EXISTS "record_locator" VARCHAR;
UPDATE "governance"."workflow_tasks"
    SET "record_locator" = ('rl_' || REPLACE(UUID_STRING(), '-', ''))
    WHERE "record_locator" IS NULL;
ALTER TABLE "governance"."workflow_tasks"
    ALTER COLUMN "record_locator" SET NOT NULL;





CREATE TABLE IF NOT EXISTS "governance"."attachments_audit"
(

    "audit_id" VARCHAR NOT NULL PRIMARY KEY
    ,"occurred_at" TIMESTAMP_TZ NOT NULL
    ,"tenant_id" VARCHAR
    ,"actor_user_name" VARCHAR NOT NULL
    ,"actor_roles" VARIANT NOT NULL
    ,"action" VARCHAR NOT NULL
    ,"outcome" VARCHAR NOT NULL
    ,"schema_name" VARCHAR NOT NULL
    ,"entity_name" VARCHAR NOT NULL
    ,"table_name" VARCHAR NOT NULL
    ,"audit_table_name" VARCHAR NOT NULL
    ,"record_id" VARCHAR
    ,"before_json" VARIANT NULL
    ,"after_json" VARIANT NULL
    ,"diff_json" VARIANT NOT NULL
    ,"policy_json" VARIANT NULL
    ,"redactions_json" VARIANT NOT NULL
    ,"chain_scope" VARCHAR NOT NULL
    ,"prev_hash" VARCHAR
    ,"event_hash" VARCHAR NOT NULL
    ,"signature" VARCHAR NULL
);


ALTER TABLE "governance"."attachments_audit"
    ADD COLUMN IF NOT EXISTS "schema_name" VARCHAR NOT NULL DEFAULT 'governance';

ALTER TABLE "governance"."attachments_audit"
    ADD COLUMN IF NOT EXISTS "entity_name" VARCHAR NOT NULL DEFAULT 'Attachment';

ALTER TABLE "governance"."attachments_audit"
    ADD COLUMN IF NOT EXISTS "table_name" VARCHAR NOT NULL DEFAULT 'attachments';

ALTER TABLE "governance"."attachments_audit"
    ADD COLUMN IF NOT EXISTS "audit_table_name" VARCHAR NOT NULL DEFAULT 'attachments_audit';


CREATE TABLE IF NOT EXISTS "governance"."checklist_items_audit"
(

    "audit_id" VARCHAR NOT NULL PRIMARY KEY
    ,"occurred_at" TIMESTAMP_TZ NOT NULL
    ,"tenant_id" VARCHAR
    ,"actor_user_name" VARCHAR NOT NULL
    ,"actor_roles" VARIANT NOT NULL
    ,"action" VARCHAR NOT NULL
    ,"outcome" VARCHAR NOT NULL
    ,"schema_name" VARCHAR NOT NULL
    ,"entity_name" VARCHAR NOT NULL
    ,"table_name" VARCHAR NOT NULL
    ,"audit_table_name" VARCHAR NOT NULL
    ,"record_id" VARCHAR
    ,"before_json" VARIANT NULL
    ,"after_json" VARIANT NULL
    ,"diff_json" VARIANT NOT NULL
    ,"policy_json" VARIANT NULL
    ,"redactions_json" VARIANT NOT NULL
    ,"chain_scope" VARCHAR NOT NULL
    ,"prev_hash" VARCHAR
    ,"event_hash" VARCHAR NOT NULL
    ,"signature" VARCHAR NULL
);


ALTER TABLE "governance"."checklist_items_audit"
    ADD COLUMN IF NOT EXISTS "schema_name" VARCHAR NOT NULL DEFAULT 'governance';

ALTER TABLE "governance"."checklist_items_audit"
    ADD COLUMN IF NOT EXISTS "entity_name" VARCHAR NOT NULL DEFAULT 'ChecklistItem';

ALTER TABLE "governance"."checklist_items_audit"
    ADD COLUMN IF NOT EXISTS "table_name" VARCHAR NOT NULL DEFAULT 'checklist_items';

ALTER TABLE "governance"."checklist_items_audit"
    ADD COLUMN IF NOT EXISTS "audit_table_name" VARCHAR NOT NULL DEFAULT 'checklist_items_audit';


CREATE TABLE IF NOT EXISTS "governance"."comments_audit"
(

    "audit_id" VARCHAR NOT NULL PRIMARY KEY
    ,"occurred_at" TIMESTAMP_TZ NOT NULL
    ,"tenant_id" VARCHAR
    ,"actor_user_name" VARCHAR NOT NULL
    ,"actor_roles" VARIANT NOT NULL
    ,"action" VARCHAR NOT NULL
    ,"outcome" VARCHAR NOT NULL
    ,"schema_name" VARCHAR NOT NULL
    ,"entity_name" VARCHAR NOT NULL
    ,"table_name" VARCHAR NOT NULL
    ,"audit_table_name" VARCHAR NOT NULL
    ,"record_id" VARCHAR
    ,"before_json" VARIANT NULL
    ,"after_json" VARIANT NULL
    ,"diff_json" VARIANT NOT NULL
    ,"policy_json" VARIANT NULL
    ,"redactions_json" VARIANT NOT NULL
    ,"chain_scope" VARCHAR NOT NULL
    ,"prev_hash" VARCHAR
    ,"event_hash" VARCHAR NOT NULL
    ,"signature" VARCHAR NULL
);


ALTER TABLE "governance"."comments_audit"
    ADD COLUMN IF NOT EXISTS "schema_name" VARCHAR NOT NULL DEFAULT 'governance';

ALTER TABLE "governance"."comments_audit"
    ADD COLUMN IF NOT EXISTS "entity_name" VARCHAR NOT NULL DEFAULT 'Comment';

ALTER TABLE "governance"."comments_audit"
    ADD COLUMN IF NOT EXISTS "table_name" VARCHAR NOT NULL DEFAULT 'comments';

ALTER TABLE "governance"."comments_audit"
    ADD COLUMN IF NOT EXISTS "audit_table_name" VARCHAR NOT NULL DEFAULT 'comments_audit';


CREATE TABLE IF NOT EXISTS "governance"."gate_reviews_audit"
(

    "audit_id" VARCHAR NOT NULL PRIMARY KEY
    ,"occurred_at" TIMESTAMP_TZ NOT NULL
    ,"tenant_id" VARCHAR
    ,"actor_user_name" VARCHAR NOT NULL
    ,"actor_roles" VARIANT NOT NULL
    ,"action" VARCHAR NOT NULL
    ,"outcome" VARCHAR NOT NULL
    ,"schema_name" VARCHAR NOT NULL
    ,"entity_name" VARCHAR NOT NULL
    ,"table_name" VARCHAR NOT NULL
    ,"audit_table_name" VARCHAR NOT NULL
    ,"record_id" VARCHAR
    ,"before_json" VARIANT NULL
    ,"after_json" VARIANT NULL
    ,"diff_json" VARIANT NOT NULL
    ,"policy_json" VARIANT NULL
    ,"redactions_json" VARIANT NOT NULL
    ,"chain_scope" VARCHAR NOT NULL
    ,"prev_hash" VARCHAR
    ,"event_hash" VARCHAR NOT NULL
    ,"signature" VARCHAR NULL
);


ALTER TABLE "governance"."gate_reviews_audit"
    ADD COLUMN IF NOT EXISTS "schema_name" VARCHAR NOT NULL DEFAULT 'governance';

ALTER TABLE "governance"."gate_reviews_audit"
    ADD COLUMN IF NOT EXISTS "entity_name" VARCHAR NOT NULL DEFAULT 'GateReview';

ALTER TABLE "governance"."gate_reviews_audit"
    ADD COLUMN IF NOT EXISTS "table_name" VARCHAR NOT NULL DEFAULT 'gate_reviews';

ALTER TABLE "governance"."gate_reviews_audit"
    ADD COLUMN IF NOT EXISTS "audit_table_name" VARCHAR NOT NULL DEFAULT 'gate_reviews_audit';


CREATE TABLE IF NOT EXISTS "governance"."gate_submissions_audit"
(

    "audit_id" VARCHAR NOT NULL PRIMARY KEY
    ,"occurred_at" TIMESTAMP_TZ NOT NULL
    ,"tenant_id" VARCHAR
    ,"actor_user_name" VARCHAR NOT NULL
    ,"actor_roles" VARIANT NOT NULL
    ,"action" VARCHAR NOT NULL
    ,"outcome" VARCHAR NOT NULL
    ,"schema_name" VARCHAR NOT NULL
    ,"entity_name" VARCHAR NOT NULL
    ,"table_name" VARCHAR NOT NULL
    ,"audit_table_name" VARCHAR NOT NULL
    ,"record_id" VARCHAR
    ,"before_json" VARIANT NULL
    ,"after_json" VARIANT NULL
    ,"diff_json" VARIANT NOT NULL
    ,"policy_json" VARIANT NULL
    ,"redactions_json" VARIANT NOT NULL
    ,"chain_scope" VARCHAR NOT NULL
    ,"prev_hash" VARCHAR
    ,"event_hash" VARCHAR NOT NULL
    ,"signature" VARCHAR NULL
);


ALTER TABLE "governance"."gate_submissions_audit"
    ADD COLUMN IF NOT EXISTS "schema_name" VARCHAR NOT NULL DEFAULT 'governance';

ALTER TABLE "governance"."gate_submissions_audit"
    ADD COLUMN IF NOT EXISTS "entity_name" VARCHAR NOT NULL DEFAULT 'GateSubmission';

ALTER TABLE "governance"."gate_submissions_audit"
    ADD COLUMN IF NOT EXISTS "table_name" VARCHAR NOT NULL DEFAULT 'gate_submissions';

ALTER TABLE "governance"."gate_submissions_audit"
    ADD COLUMN IF NOT EXISTS "audit_table_name" VARCHAR NOT NULL DEFAULT 'gate_submissions_audit';


CREATE TABLE IF NOT EXISTS "governance"."meetings_audit"
(

    "audit_id" VARCHAR NOT NULL PRIMARY KEY
    ,"occurred_at" TIMESTAMP_TZ NOT NULL
    ,"tenant_id" VARCHAR
    ,"actor_user_name" VARCHAR NOT NULL
    ,"actor_roles" VARIANT NOT NULL
    ,"action" VARCHAR NOT NULL
    ,"outcome" VARCHAR NOT NULL
    ,"schema_name" VARCHAR NOT NULL
    ,"entity_name" VARCHAR NOT NULL
    ,"table_name" VARCHAR NOT NULL
    ,"audit_table_name" VARCHAR NOT NULL
    ,"record_id" VARCHAR
    ,"before_json" VARIANT NULL
    ,"after_json" VARIANT NULL
    ,"diff_json" VARIANT NOT NULL
    ,"policy_json" VARIANT NULL
    ,"redactions_json" VARIANT NOT NULL
    ,"chain_scope" VARCHAR NOT NULL
    ,"prev_hash" VARCHAR
    ,"event_hash" VARCHAR NOT NULL
    ,"signature" VARCHAR NULL
);


ALTER TABLE "governance"."meetings_audit"
    ADD COLUMN IF NOT EXISTS "schema_name" VARCHAR NOT NULL DEFAULT 'governance';

ALTER TABLE "governance"."meetings_audit"
    ADD COLUMN IF NOT EXISTS "entity_name" VARCHAR NOT NULL DEFAULT 'Meeting';

ALTER TABLE "governance"."meetings_audit"
    ADD COLUMN IF NOT EXISTS "table_name" VARCHAR NOT NULL DEFAULT 'meetings';

ALTER TABLE "governance"."meetings_audit"
    ADD COLUMN IF NOT EXISTS "audit_table_name" VARCHAR NOT NULL DEFAULT 'meetings_audit';


CREATE TABLE IF NOT EXISTS "governance"."projects_audit"
(

    "audit_id" VARCHAR NOT NULL PRIMARY KEY
    ,"occurred_at" TIMESTAMP_TZ NOT NULL
    ,"tenant_id" VARCHAR
    ,"actor_user_name" VARCHAR NOT NULL
    ,"actor_roles" VARIANT NOT NULL
    ,"action" VARCHAR NOT NULL
    ,"outcome" VARCHAR NOT NULL
    ,"schema_name" VARCHAR NOT NULL
    ,"entity_name" VARCHAR NOT NULL
    ,"table_name" VARCHAR NOT NULL
    ,"audit_table_name" VARCHAR NOT NULL
    ,"record_id" VARCHAR
    ,"before_json" VARIANT NULL
    ,"after_json" VARIANT NULL
    ,"diff_json" VARIANT NOT NULL
    ,"policy_json" VARIANT NULL
    ,"redactions_json" VARIANT NOT NULL
    ,"chain_scope" VARCHAR NOT NULL
    ,"prev_hash" VARCHAR
    ,"event_hash" VARCHAR NOT NULL
    ,"signature" VARCHAR NULL
);


ALTER TABLE "governance"."projects_audit"
    ADD COLUMN IF NOT EXISTS "schema_name" VARCHAR NOT NULL DEFAULT 'governance';

ALTER TABLE "governance"."projects_audit"
    ADD COLUMN IF NOT EXISTS "entity_name" VARCHAR NOT NULL DEFAULT 'Project';

ALTER TABLE "governance"."projects_audit"
    ADD COLUMN IF NOT EXISTS "table_name" VARCHAR NOT NULL DEFAULT 'projects';

ALTER TABLE "governance"."projects_audit"
    ADD COLUMN IF NOT EXISTS "audit_table_name" VARCHAR NOT NULL DEFAULT 'projects_audit';


CREATE TABLE IF NOT EXISTS "governance"."project_approvals_audit"
(

    "audit_id" VARCHAR NOT NULL PRIMARY KEY
    ,"occurred_at" TIMESTAMP_TZ NOT NULL
    ,"tenant_id" VARCHAR
    ,"actor_user_name" VARCHAR NOT NULL
    ,"actor_roles" VARIANT NOT NULL
    ,"action" VARCHAR NOT NULL
    ,"outcome" VARCHAR NOT NULL
    ,"schema_name" VARCHAR NOT NULL
    ,"entity_name" VARCHAR NOT NULL
    ,"table_name" VARCHAR NOT NULL
    ,"audit_table_name" VARCHAR NOT NULL
    ,"record_id" VARCHAR
    ,"before_json" VARIANT NULL
    ,"after_json" VARIANT NULL
    ,"diff_json" VARIANT NOT NULL
    ,"policy_json" VARIANT NULL
    ,"redactions_json" VARIANT NOT NULL
    ,"chain_scope" VARCHAR NOT NULL
    ,"prev_hash" VARCHAR
    ,"event_hash" VARCHAR NOT NULL
    ,"signature" VARCHAR NULL
);


ALTER TABLE "governance"."project_approvals_audit"
    ADD COLUMN IF NOT EXISTS "schema_name" VARCHAR NOT NULL DEFAULT 'governance';

ALTER TABLE "governance"."project_approvals_audit"
    ADD COLUMN IF NOT EXISTS "entity_name" VARCHAR NOT NULL DEFAULT 'ProjectApproval';

ALTER TABLE "governance"."project_approvals_audit"
    ADD COLUMN IF NOT EXISTS "table_name" VARCHAR NOT NULL DEFAULT 'project_approvals';

ALTER TABLE "governance"."project_approvals_audit"
    ADD COLUMN IF NOT EXISTS "audit_table_name" VARCHAR NOT NULL DEFAULT 'project_approvals_audit';


CREATE TABLE IF NOT EXISTS "governance"."project_fields_audit"
(

    "audit_id" VARCHAR NOT NULL PRIMARY KEY
    ,"occurred_at" TIMESTAMP_TZ NOT NULL
    ,"tenant_id" VARCHAR
    ,"actor_user_name" VARCHAR NOT NULL
    ,"actor_roles" VARIANT NOT NULL
    ,"action" VARCHAR NOT NULL
    ,"outcome" VARCHAR NOT NULL
    ,"schema_name" VARCHAR NOT NULL
    ,"entity_name" VARCHAR NOT NULL
    ,"table_name" VARCHAR NOT NULL
    ,"audit_table_name" VARCHAR NOT NULL
    ,"record_id" VARCHAR
    ,"before_json" VARIANT NULL
    ,"after_json" VARIANT NULL
    ,"diff_json" VARIANT NOT NULL
    ,"policy_json" VARIANT NULL
    ,"redactions_json" VARIANT NOT NULL
    ,"chain_scope" VARCHAR NOT NULL
    ,"prev_hash" VARCHAR
    ,"event_hash" VARCHAR NOT NULL
    ,"signature" VARCHAR NULL
);


ALTER TABLE "governance"."project_fields_audit"
    ADD COLUMN IF NOT EXISTS "schema_name" VARCHAR NOT NULL DEFAULT 'governance';

ALTER TABLE "governance"."project_fields_audit"
    ADD COLUMN IF NOT EXISTS "entity_name" VARCHAR NOT NULL DEFAULT 'ProjectField';

ALTER TABLE "governance"."project_fields_audit"
    ADD COLUMN IF NOT EXISTS "table_name" VARCHAR NOT NULL DEFAULT 'project_fields';

ALTER TABLE "governance"."project_fields_audit"
    ADD COLUMN IF NOT EXISTS "audit_table_name" VARCHAR NOT NULL DEFAULT 'project_fields_audit';


CREATE TABLE IF NOT EXISTS "governance"."project_stakeholders_audit"
(

    "audit_id" VARCHAR NOT NULL PRIMARY KEY
    ,"occurred_at" TIMESTAMP_TZ NOT NULL
    ,"tenant_id" VARCHAR
    ,"actor_user_name" VARCHAR NOT NULL
    ,"actor_roles" VARIANT NOT NULL
    ,"action" VARCHAR NOT NULL
    ,"outcome" VARCHAR NOT NULL
    ,"schema_name" VARCHAR NOT NULL
    ,"entity_name" VARCHAR NOT NULL
    ,"table_name" VARCHAR NOT NULL
    ,"audit_table_name" VARCHAR NOT NULL
    ,"record_id" VARCHAR
    ,"before_json" VARIANT NULL
    ,"after_json" VARIANT NULL
    ,"diff_json" VARIANT NOT NULL
    ,"policy_json" VARIANT NULL
    ,"redactions_json" VARIANT NOT NULL
    ,"chain_scope" VARCHAR NOT NULL
    ,"prev_hash" VARCHAR
    ,"event_hash" VARCHAR NOT NULL
    ,"signature" VARCHAR NULL
);


ALTER TABLE "governance"."project_stakeholders_audit"
    ADD COLUMN IF NOT EXISTS "schema_name" VARCHAR NOT NULL DEFAULT 'governance';

ALTER TABLE "governance"."project_stakeholders_audit"
    ADD COLUMN IF NOT EXISTS "entity_name" VARCHAR NOT NULL DEFAULT 'ProjectStakeholder';

ALTER TABLE "governance"."project_stakeholders_audit"
    ADD COLUMN IF NOT EXISTS "table_name" VARCHAR NOT NULL DEFAULT 'project_stakeholders';

ALTER TABLE "governance"."project_stakeholders_audit"
    ADD COLUMN IF NOT EXISTS "audit_table_name" VARCHAR NOT NULL DEFAULT 'project_stakeholders_audit';


CREATE TABLE IF NOT EXISTS "governance"."risk_items_audit"
(

    "audit_id" VARCHAR NOT NULL PRIMARY KEY
    ,"occurred_at" TIMESTAMP_TZ NOT NULL
    ,"tenant_id" VARCHAR
    ,"actor_user_name" VARCHAR NOT NULL
    ,"actor_roles" VARIANT NOT NULL
    ,"action" VARCHAR NOT NULL
    ,"outcome" VARCHAR NOT NULL
    ,"schema_name" VARCHAR NOT NULL
    ,"entity_name" VARCHAR NOT NULL
    ,"table_name" VARCHAR NOT NULL
    ,"audit_table_name" VARCHAR NOT NULL
    ,"record_id" VARCHAR
    ,"before_json" VARIANT NULL
    ,"after_json" VARIANT NULL
    ,"diff_json" VARIANT NOT NULL
    ,"policy_json" VARIANT NULL
    ,"redactions_json" VARIANT NOT NULL
    ,"chain_scope" VARCHAR NOT NULL
    ,"prev_hash" VARCHAR
    ,"event_hash" VARCHAR NOT NULL
    ,"signature" VARCHAR NULL
);


ALTER TABLE "governance"."risk_items_audit"
    ADD COLUMN IF NOT EXISTS "schema_name" VARCHAR NOT NULL DEFAULT 'governance';

ALTER TABLE "governance"."risk_items_audit"
    ADD COLUMN IF NOT EXISTS "entity_name" VARCHAR NOT NULL DEFAULT 'RiskItem';

ALTER TABLE "governance"."risk_items_audit"
    ADD COLUMN IF NOT EXISTS "table_name" VARCHAR NOT NULL DEFAULT 'risk_items';

ALTER TABLE "governance"."risk_items_audit"
    ADD COLUMN IF NOT EXISTS "audit_table_name" VARCHAR NOT NULL DEFAULT 'risk_items_audit';


CREATE TABLE IF NOT EXISTS "governance"."task_assignments_audit"
(

    "audit_id" VARCHAR NOT NULL PRIMARY KEY
    ,"occurred_at" TIMESTAMP_TZ NOT NULL
    ,"tenant_id" VARCHAR
    ,"actor_user_name" VARCHAR NOT NULL
    ,"actor_roles" VARIANT NOT NULL
    ,"action" VARCHAR NOT NULL
    ,"outcome" VARCHAR NOT NULL
    ,"schema_name" VARCHAR NOT NULL
    ,"entity_name" VARCHAR NOT NULL
    ,"table_name" VARCHAR NOT NULL
    ,"audit_table_name" VARCHAR NOT NULL
    ,"record_id" VARCHAR
    ,"before_json" VARIANT NULL
    ,"after_json" VARIANT NULL
    ,"diff_json" VARIANT NOT NULL
    ,"policy_json" VARIANT NULL
    ,"redactions_json" VARIANT NOT NULL
    ,"chain_scope" VARCHAR NOT NULL
    ,"prev_hash" VARCHAR
    ,"event_hash" VARCHAR NOT NULL
    ,"signature" VARCHAR NULL
);


ALTER TABLE "governance"."task_assignments_audit"
    ADD COLUMN IF NOT EXISTS "schema_name" VARCHAR NOT NULL DEFAULT 'governance';

ALTER TABLE "governance"."task_assignments_audit"
    ADD COLUMN IF NOT EXISTS "entity_name" VARCHAR NOT NULL DEFAULT 'TaskAssignment';

ALTER TABLE "governance"."task_assignments_audit"
    ADD COLUMN IF NOT EXISTS "table_name" VARCHAR NOT NULL DEFAULT 'task_assignments';

ALTER TABLE "governance"."task_assignments_audit"
    ADD COLUMN IF NOT EXISTS "audit_table_name" VARCHAR NOT NULL DEFAULT 'task_assignments_audit';


CREATE TABLE IF NOT EXISTS "governance"."users_audit"
(

    "audit_id" VARCHAR NOT NULL PRIMARY KEY
    ,"occurred_at" TIMESTAMP_TZ NOT NULL
    ,"tenant_id" VARCHAR
    ,"actor_user_name" VARCHAR NOT NULL
    ,"actor_roles" VARIANT NOT NULL
    ,"action" VARCHAR NOT NULL
    ,"outcome" VARCHAR NOT NULL
    ,"schema_name" VARCHAR NOT NULL
    ,"entity_name" VARCHAR NOT NULL
    ,"table_name" VARCHAR NOT NULL
    ,"audit_table_name" VARCHAR NOT NULL
    ,"record_id" VARCHAR
    ,"before_json" VARIANT NULL
    ,"after_json" VARIANT NULL
    ,"diff_json" VARIANT NOT NULL
    ,"policy_json" VARIANT NULL
    ,"redactions_json" VARIANT NOT NULL
    ,"chain_scope" VARCHAR NOT NULL
    ,"prev_hash" VARCHAR
    ,"event_hash" VARCHAR NOT NULL
    ,"signature" VARCHAR NULL
);


ALTER TABLE "governance"."users_audit"
    ADD COLUMN IF NOT EXISTS "schema_name" VARCHAR NOT NULL DEFAULT 'governance';

ALTER TABLE "governance"."users_audit"
    ADD COLUMN IF NOT EXISTS "entity_name" VARCHAR NOT NULL DEFAULT 'User';

ALTER TABLE "governance"."users_audit"
    ADD COLUMN IF NOT EXISTS "table_name" VARCHAR NOT NULL DEFAULT 'users';

ALTER TABLE "governance"."users_audit"
    ADD COLUMN IF NOT EXISTS "audit_table_name" VARCHAR NOT NULL DEFAULT 'users_audit';


CREATE TABLE IF NOT EXISTS "governance"."workflow_instances_audit"
(

    "audit_id" VARCHAR NOT NULL PRIMARY KEY
    ,"occurred_at" TIMESTAMP_TZ NOT NULL
    ,"tenant_id" VARCHAR
    ,"actor_user_name" VARCHAR NOT NULL
    ,"actor_roles" VARIANT NOT NULL
    ,"action" VARCHAR NOT NULL
    ,"outcome" VARCHAR NOT NULL
    ,"schema_name" VARCHAR NOT NULL
    ,"entity_name" VARCHAR NOT NULL
    ,"table_name" VARCHAR NOT NULL
    ,"audit_table_name" VARCHAR NOT NULL
    ,"record_id" VARCHAR
    ,"before_json" VARIANT NULL
    ,"after_json" VARIANT NULL
    ,"diff_json" VARIANT NOT NULL
    ,"policy_json" VARIANT NULL
    ,"redactions_json" VARIANT NOT NULL
    ,"chain_scope" VARCHAR NOT NULL
    ,"prev_hash" VARCHAR
    ,"event_hash" VARCHAR NOT NULL
    ,"signature" VARCHAR NULL
);


ALTER TABLE "governance"."workflow_instances_audit"
    ADD COLUMN IF NOT EXISTS "schema_name" VARCHAR NOT NULL DEFAULT 'governance';

ALTER TABLE "governance"."workflow_instances_audit"
    ADD COLUMN IF NOT EXISTS "entity_name" VARCHAR NOT NULL DEFAULT 'WorkflowInstance';

ALTER TABLE "governance"."workflow_instances_audit"
    ADD COLUMN IF NOT EXISTS "table_name" VARCHAR NOT NULL DEFAULT 'workflow_instances';

ALTER TABLE "governance"."workflow_instances_audit"
    ADD COLUMN IF NOT EXISTS "audit_table_name" VARCHAR NOT NULL DEFAULT 'workflow_instances_audit';


CREATE TABLE IF NOT EXISTS "governance"."workflow_stages_audit"
(

    "audit_id" VARCHAR NOT NULL PRIMARY KEY
    ,"occurred_at" TIMESTAMP_TZ NOT NULL
    ,"tenant_id" VARCHAR
    ,"actor_user_name" VARCHAR NOT NULL
    ,"actor_roles" VARIANT NOT NULL
    ,"action" VARCHAR NOT NULL
    ,"outcome" VARCHAR NOT NULL
    ,"schema_name" VARCHAR NOT NULL
    ,"entity_name" VARCHAR NOT NULL
    ,"table_name" VARCHAR NOT NULL
    ,"audit_table_name" VARCHAR NOT NULL
    ,"record_id" VARCHAR
    ,"before_json" VARIANT NULL
    ,"after_json" VARIANT NULL
    ,"diff_json" VARIANT NOT NULL
    ,"policy_json" VARIANT NULL
    ,"redactions_json" VARIANT NOT NULL
    ,"chain_scope" VARCHAR NOT NULL
    ,"prev_hash" VARCHAR
    ,"event_hash" VARCHAR NOT NULL
    ,"signature" VARCHAR NULL
);


ALTER TABLE "governance"."workflow_stages_audit"
    ADD COLUMN IF NOT EXISTS "schema_name" VARCHAR NOT NULL DEFAULT 'governance';

ALTER TABLE "governance"."workflow_stages_audit"
    ADD COLUMN IF NOT EXISTS "entity_name" VARCHAR NOT NULL DEFAULT 'WorkflowStage';

ALTER TABLE "governance"."workflow_stages_audit"
    ADD COLUMN IF NOT EXISTS "table_name" VARCHAR NOT NULL DEFAULT 'workflow_stages';

ALTER TABLE "governance"."workflow_stages_audit"
    ADD COLUMN IF NOT EXISTS "audit_table_name" VARCHAR NOT NULL DEFAULT 'workflow_stages_audit';


CREATE TABLE IF NOT EXISTS "governance"."workflow_stage_definitions_audit"
(

    "audit_id" VARCHAR NOT NULL PRIMARY KEY
    ,"occurred_at" TIMESTAMP_TZ NOT NULL
    ,"tenant_id" VARCHAR
    ,"actor_user_name" VARCHAR NOT NULL
    ,"actor_roles" VARIANT NOT NULL
    ,"action" VARCHAR NOT NULL
    ,"outcome" VARCHAR NOT NULL
    ,"schema_name" VARCHAR NOT NULL
    ,"entity_name" VARCHAR NOT NULL
    ,"table_name" VARCHAR NOT NULL
    ,"audit_table_name" VARCHAR NOT NULL
    ,"record_id" VARCHAR
    ,"before_json" VARIANT NULL
    ,"after_json" VARIANT NULL
    ,"diff_json" VARIANT NOT NULL
    ,"policy_json" VARIANT NULL
    ,"redactions_json" VARIANT NOT NULL
    ,"chain_scope" VARCHAR NOT NULL
    ,"prev_hash" VARCHAR
    ,"event_hash" VARCHAR NOT NULL
    ,"signature" VARCHAR NULL
);


ALTER TABLE "governance"."workflow_stage_definitions_audit"
    ADD COLUMN IF NOT EXISTS "schema_name" VARCHAR NOT NULL DEFAULT 'governance';

ALTER TABLE "governance"."workflow_stage_definitions_audit"
    ADD COLUMN IF NOT EXISTS "entity_name" VARCHAR NOT NULL DEFAULT 'WorkflowStageDefinition';

ALTER TABLE "governance"."workflow_stage_definitions_audit"
    ADD COLUMN IF NOT EXISTS "table_name" VARCHAR NOT NULL DEFAULT 'workflow_stage_definitions';

ALTER TABLE "governance"."workflow_stage_definitions_audit"
    ADD COLUMN IF NOT EXISTS "audit_table_name" VARCHAR NOT NULL DEFAULT 'workflow_stage_definitions_audit';


CREATE TABLE IF NOT EXISTS "governance"."workflow_tasks_audit"
(

    "audit_id" VARCHAR NOT NULL PRIMARY KEY
    ,"occurred_at" TIMESTAMP_TZ NOT NULL
    ,"tenant_id" VARCHAR
    ,"actor_user_name" VARCHAR NOT NULL
    ,"actor_roles" VARIANT NOT NULL
    ,"action" VARCHAR NOT NULL
    ,"outcome" VARCHAR NOT NULL
    ,"schema_name" VARCHAR NOT NULL
    ,"entity_name" VARCHAR NOT NULL
    ,"table_name" VARCHAR NOT NULL
    ,"audit_table_name" VARCHAR NOT NULL
    ,"record_id" VARCHAR
    ,"before_json" VARIANT NULL
    ,"after_json" VARIANT NULL
    ,"diff_json" VARIANT NOT NULL
    ,"policy_json" VARIANT NULL
    ,"redactions_json" VARIANT NOT NULL
    ,"chain_scope" VARCHAR NOT NULL
    ,"prev_hash" VARCHAR
    ,"event_hash" VARCHAR NOT NULL
    ,"signature" VARCHAR NULL
);


ALTER TABLE "governance"."workflow_tasks_audit"
    ADD COLUMN IF NOT EXISTS "schema_name" VARCHAR NOT NULL DEFAULT 'governance';

ALTER TABLE "governance"."workflow_tasks_audit"
    ADD COLUMN IF NOT EXISTS "entity_name" VARCHAR NOT NULL DEFAULT 'WorkflowTask';

ALTER TABLE "governance"."workflow_tasks_audit"
    ADD COLUMN IF NOT EXISTS "table_name" VARCHAR NOT NULL DEFAULT 'workflow_tasks';

ALTER TABLE "governance"."workflow_tasks_audit"
    ADD COLUMN IF NOT EXISTS "audit_table_name" VARCHAR NOT NULL DEFAULT 'workflow_tasks_audit';
