//
// /backend/src/routes/Governance.rs
//    Defines routes for governance GraphQL requests
//    Generated by app_gen.
//
#![allow(dead_code)]

use appfw_runtime::security::SecurityConfig;
use axum::Router;
use std::sync::Arc;

use crate::data::data_access::DataAccess;
use crate::handlers::governance::*;
use crate::platform::{auth::JwtAuthConfig, graphql_gateway};

pub async fn get_routes(
    data_access: Arc<DataAccess>,
    auth: JwtAuthConfig,
    security: SecurityConfig,
) -> Router {
    let governance_schema = async_graphql::Schema::build(
        GovernanceQuery::default(),
        GovernanceMutation::default(),
        async_graphql::EmptySubscription,
    )
    .data(data_access.clone())
    .limit_depth(security.graphql_max_depth)
    .limit_complexity(security.graphql_max_complexity)
    .finish();
    let governance_introspection_schema = async_graphql::Schema::build(
        GovernanceQuery::default(),
        GovernanceMutation::default(),
        async_graphql::EmptySubscription,
    )
    .data(data_access.clone())
    .introspection_only()
    .finish();

    graphql_gateway::mount(
        "/governance",
        governance_schema,
        governance_introspection_schema,
        auth,
        security,
    )
}
