//
// /backend/src/routes/Governance.rs
//    Defines routes for governance GraphQL requests
//    Generated by app_gen.
//
#![allow(dead_code)]

use appfw_runtime::{
    routing::runtime_graphql_schema_routes, security::SecurityConfig, RuntimeAuthState,
};
use axum::Router;
use std::sync::Arc;

use crate::data::data_access::DataAccess;
use crate::handlers::governance::*;

pub async fn get_routes(
    data_access: Arc<DataAccess>,
    app_state: RuntimeAuthState,
    security: SecurityConfig,
) -> Router {
    let governance_schema = async_graphql::Schema::build(
        GovernanceQuery::default(),
        GovernanceMutation::default(),
        async_graphql::EmptySubscription,
    )
    .data(data_access.clone())
    .limit_depth(security.graphql_max_depth)
    .limit_complexity(security.graphql_max_complexity)
    .finish();
    let governance_introspection_schema = async_graphql::Schema::build(
        GovernanceQuery::default(),
        GovernanceMutation::default(),
        async_graphql::EmptySubscription,
    )
    .data(data_access.clone())
    .introspection_only()
    .finish();

    runtime_graphql_schema_routes(
        "/governance",
        governance_schema,
        governance_introspection_schema,
        app_state,
        security,
    )
}
