//
// /backend/src/routes/System.rs
//    Defines routes for system GraphQL requests
//    Generated by app_gen.
//
#![allow(dead_code)]

use appfw_runtime::security::SecurityConfig;
use axum::Router;
use std::sync::Arc;

use crate::data::data_access::DataAccess;
use crate::handlers::system::*;
use crate::platform::{auth::JwtAuthConfig, graphql_gateway};

pub async fn get_routes(
    data_access: Arc<DataAccess>,
    auth: JwtAuthConfig,
    security: SecurityConfig,
) -> Router {
    let system_schema = async_graphql::Schema::build(
        SystemQuery::default(),
        SystemMutation::default(),
        async_graphql::EmptySubscription,
    )
    .data(data_access.clone())
    .limit_depth(security.graphql_max_depth)
    .limit_complexity(security.graphql_max_complexity)
    .finish();
    let system_introspection_schema = async_graphql::Schema::build(
        SystemQuery::default(),
        SystemMutation::default(),
        async_graphql::EmptySubscription,
    )
    .data(data_access.clone())
    .introspection_only()
    .finish();

    graphql_gateway::mount(
        "/system",
        system_schema,
        system_introspection_schema,
        auth,
        security,
    )
}
