//
// Generated by app_gen for governance.
//   - From tests yaml
//

#[cfg(test)]
mod tests {

    use anyhow::Result;
    use serde_json::json;

    use crate::harness::TestContext;

    #[tokio::test]
    async fn test_projects_scenario() -> Result<()> {
        let mut ctx = TestContext::from_env()?;

        step_create_project(&mut ctx).await?;

        step_find_project(&mut ctx).await?;

        step_update_project_with_stale_version(&mut ctx).await?;

        Ok(())
    }

    async fn step_create_project(ctx: &mut TestContext) -> Result<()> {
        // Description: create a project as admin
        println!("*** Test description: create a project as admin ***");

        let req = r#"
      mutation($input: InputProject!){
        createProject(input: $input){
            id,project_number,project_name,business_unit,manager_id,status,priority,version
        }
      }
    "#;

        let variables = Some(json!({
        "input": {"project_number":"GOV-TEST-0001","project_name":"Test Governance Project","business_unit":"Information Technology","manager_id":"b0000000-0000-4000-8000-000000000001","priority":"MEDIUM","status":"DRAFT","version":0}
        }));

        let gql_result = ctx
            .execute_graphql("pdsh_admin", "governance", req, variables)
            .await?;
        println!("create_project GraphQL result: {:?}", gql_result);

        ctx.expect_data(
      "create_project",
      &gql_result,
      "createProject",
      json!({"project_number":"GOV-TEST-0001","project_name":"Test Governance Project","business_unit":"Information Technology","status":"DRAFT"}),
      Some("create_project_result"),
    )?;

        Ok(())
    }

    async fn step_find_project(ctx: &mut TestContext) -> Result<()> {
        // Description: find the project with its NavToOne manager
        println!("*** Test description: find the project with its NavToOne manager ***");

        let req = r#"
      query($id: String!){
        findProject(id: $id){
            id,project_name,manager_id,manager { id,email },version
        }
      }
    "#;

        let variables = Some(json!({
        "id": ctx.result_value("create_project_result.id")?
        }));

        let gql_result = ctx
            .execute_graphql("pdsh_admin", "governance", req, variables)
            .await?;
        println!("find_project GraphQL result: {:?}", gql_result);

        ctx.expect_data(
      "find_project",
      &gql_result,
      "findProject",
      json!({"project_name":"Test Governance Project","manager_id":"b0000000-0000-4000-8000-000000000001"}),
      Some("find_project_result"),
    )?;

        Ok(())
    }

    async fn step_update_project_with_stale_version(ctx: &mut TestContext) -> Result<()> {
        // Description: a stale optimistic-lock version is rejected (concurrency facet)
        println!("*** Test description: a stale optimistic-lock version is rejected (concurrency facet) ***");

        let req = r#"
      mutation($input: InputProject!){
        updateProject(input: $input){
            id,business_unit,version
        }
      }
    "#;

        let variables = Some(json!({
        "input": ctx.result_map(
              "create_project_result",
              Some(serde_json::from_value::<serde_json::Map<String, serde_json::Value>>(json!({"business_unit":"Finance","version":1}))?)
            )?
        }));

        let gql_result = ctx
            .execute_graphql("pdsh_admin", "governance", req, variables)
            .await?;
        println!(
            "update_project_with_stale_version GraphQL result: {:?}",
            gql_result
        );

        ctx.expect_error(
            "update_project_with_stale_version",
            &gql_result,
            json!({"message":"invalid key or version","path":["updateProject"]}),
        )?;

        Ok(())
    }
}
