//
// Generated by app_gen for governance.
//   - From tests yaml
//

#[cfg(test)]
mod tests {

    use anyhow::Result;
    use serde_json::json;

    use crate::harness::TestContext;

    #[tokio::test]
    async fn test_users_scenario() -> Result<()> {
        let mut ctx = TestContext::from_env()?;

        step_find_seeded_admin_user(&mut ctx).await?;

        Ok(())
    }

    async fn step_find_seeded_admin_user(ctx: &mut TestContext) -> Result<()> {
        // Description: the seeded admin demo user is retrievable
        println!("*** Test description: the seeded admin demo user is retrievable ***");

        let req = r#"
      query($id: String!){
        findUser(id: $id){
            id,email,username,role,is_active
        }
      }
    "#;

        let variables = Some(json!({
        "id": "b0000000-0000-4000-8000-000000000001"
        }));

        let gql_result = ctx
            .execute_graphql("pdsh_admin", "governance", req, variables)
            .await?;
        println!("find_seeded_admin_user GraphQL result: {:?}", gql_result);

        ctx.expect_data(
      "find_seeded_admin_user",
      &gql_result,
      "findUser",
      json!({"email":"admin@abchealth.com","username":"admin","role":"ADMIN","is_active":true}),
      None,
    )?;

        Ok(())
    }
}
